### PR TITLE
imake clean-up: remove non-present buildlogic

### PR DESCRIPTION
**Pull request by sunweaver**
This PR removes several unused lines of build logic from various imake files.

This PR depends on merging https://github.com/ArcticaProject/nx-libs/pull/16 first.

### CODE REVIEW

**Comment by sunweaver** [comment]
@Ionic: This PR is rather tricky I guess and does probably not clean-up everything in imake, but it drops quite a tremendous amount of more lines of imake build-logic, that we will never need in NX.

If you feel that the diff is too unclean, please report back early and I will sit on it again (already spent a couple of hours with it...).

**Comment by sunweaver** [comment]
@Ionic: I fixed all of your comments for commit "imake cleanup: Break up multiple vars into individual lines to ease further..." and force-pushed again.

**Comment by Ionic** [comment]
Uh, my comments are all gone :(

Looks like I commented on an outdated diff: https://github.com/sunweaver/nx-libs/commit/e2b996aaf8fb9f7e145251b938aa79091f5a64a1

(Shouldn't be a real problem, though, as the content probably stayed mostly the same.)

**Comment by sunweaver** [comment]
@Ionic: I have fixed all your remarks on this PR and rebased against latest 3.6.x branch. Thanks for your input. I have pushed the fixes as individual commits for now. I'd appreciate a second glance of yours.

I will rebase all the commits marked with "rebase: <comment>" once you have taken a second look.

**Comment by Ionic** [comment]
Okay, can't see anything funny. Looks good to me!

**Comment by sunweaver** [comment]
@Ionic: ok, rebased and force-pushed. Please merge. THANKS!

**Pull request merged**
