### PR TITLE
Introduce SetNotifyFd ABI to nxagent Xserver

### PR DESCRIPTION
**Pull request by sunweaver**
This PR requires PR #330 to be merged.

The SetNotifyFd ABI is needed for building against libXfont2 (i.e. for a +/- clean cherry-pick from X.org).

### CODE REVIEW

**Comment by Ionic** [comment]
Looks okay in general. At least some of this work is highly obsolete, though, as upstream rewrote most of this to not use lists and switched to an epoll-based internal code, but I figure backporting this was too invasive/not worth the effort for now.

Please rebase.

**Comment by sunweaver** [comment]
@Ionic: rebased. Thanks for reviewing!

**Comment by sunweaver** [comment]
@Ionic: and... the epoll-based rewrite is on my list. ABI introduction (this PR) first.

**Comment by uli42** [comment]
On Fri, Mar 17, 2017 at 9:49 AM, Mike Gabriel <notifications@github.com> wrote:
> @Ionic: and... the epoll-based rewrite is on my list. ABI introduction (this
> PR) first.

1,5 years ago I have tried compiling nxagent with poll instead of
select. This compiled, but did not work. I guess this is not simple...

Uli

**Comment by sunweaver** [comment]
Hi Uli,

On  Fr 17 Mär 2017 09:53:52 CET, Ulrich Sibiller wrote:

> On Fri, Mar 17, 2017 at 9:49 AM, Mike Gabriel  
> <notifications@github.com> wrote:
>> @Ionic: and... the epoll-based rewrite is on my list. ABI introduction (this
>> PR) first.
>
> 1,5 years ago I have tried compiling nxagent with poll instead of
> select. This compiled, but did not work. I guess this is not simple...
>
> Uli

Right... I remember... Ack'ed here!

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Pull request merged**
