### PR TITLE
Pr/window resize bug

### PR DESCRIPTION
**Pull request by uli42**

### CODE REVIEW

**Comment by sunweaver** [comment]
@uli42: I won't get to reviewing this before 2nd week of August. (Currently on VAC)

**Comment by sunweaver** [comment]
@uli42: I also see faliing checks (travis).

**Comment by uli42** [comment]
Failing checks will happen until Marios PVS fix is merged.

**Review by sunweaver — APPROVED** [review]
LGTM; I spotted two issues in commit messages which I have amended (not working bug closure, typo).

**Comment by sunweaver** [comment]
I will wait for travis builds to succeed, then merge.

**Pull request merged**
