### PR TITLE
nxagent: implement RPATH/RUNPATH override for libX11. 

### PR DESCRIPTION
**Pull request by Ionic**
As discussed in ArcticaProject/nx-libs#610, we need a way to load libNX_X11 as a fake version of libX11 into nxagent's address space.

For doing so, we have to link against libX11 at build-time and specify a(n) RPATH/RUNPATH to our libX11 -> libNX_X11 compat symlinks.

This commit is essentially doing a cross between options 3 and 4 discussed in the provided GH issue.

We link libX11 early (before specifying -Lcompat_symlinks_dir), so that the linker finds the "real" libX11 version with the libX11 SONAME. This leads to our binary depending upon both libX11 and libNX_X11 SONAMEs. We already always added RPATH/RUNPATH, but these values are not passed down
to dependent libraries.

What happens at run-time is that the loader searches for a libX11 SONAME, takes RPATH/RUNPATH into account and loads our libNX_X11 library instead via the compat symlinks. This satisfies the libX11 SONAME and dependent libraries will *not* load the system libX11 version again.

Debian's dpkg-shlibdeps isn't quite happy about this mismatching SONAME situation, so instruct it to look the other way while we're minding our business.

Additionally, also do this for nxcompshad. Not really necessary, since nxagent is the only consumer and nxcompshad itself will not cause any trouble, but if we ever decide to link nxcompshad standalone to any other binary than this will come in handy.

Fixes: ArcticaProject/nx-libs#610

### CODE REVIEW

**Comment by Ionic** [comment]
With these changes, linking looks correct on both Debian and OpenSuSE Tumbleweed.

Examples:

Debian Unstable:
```
root@apgunner~src/nvidia/387(svn)-[387:7585] #  ldd /usr/lib/x86_64-linux-gnu/libXcomp.so
	linux-vdso.so.1 (0x00007ffe6b7e4000)
	libjpeg.so.62 => /usr/lib/x86_64-linux-gnu/libjpeg.so.62 (0x00007fcdf364d000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fcdf341a000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fcdf3200000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fcdf2e81000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fcdf2b6e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcdf27cb000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fcdf25b4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcdf3bd6000)
[2 running job(s)] {history#606}  2:57:15 17-12-26
root@apgunner~src/nvidia/387(svn)-[387:7585] #  ldd /usr/lib/x86_64-linux-gnu/libXcompshad.so
	linux-vdso.so.1 (0x00007fffc1b75000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/nx/X11/libX11.so.6 (0x00007f1af8995000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f1af8783000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f1af8580000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f1af837a000)
	libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f1af816f000)
	libXtst.so.6 => /usr/lib/x86_64-linux-gnu/libXtst.so.6 (0x00007f1af7f69000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1af7bea000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1af78d7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1af7534000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1af731d000)
	libXcomp.so.3 => /usr/lib/x86_64-linux-gnu/libXcomp.so.3 (0x00007f1af6ffd000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1af6ddf000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f1af6bd5000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f1af69c5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1af8ee4000)
	libjpeg.so.62 => /usr/lib/x86_64-linux-gnu/libjpeg.so.62 (0x00007f1af675c000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f1af6529000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1af630f000)
```

OpenSuSE Tumbleweed:
```
opensuse-tumbleweed:~ #  ldd $(which nxagent)
	linux-vdso.so.1 (0x00007ffc011d9000)
	libX11.so.6 => /usr/lib64/nx/X11/libX11.so.6 (0x00007fc1fbc0f000)
	libXcomp.so.3 => /usr/lib64/libXcomp.so.3 (0x00007fc1fb8d6000)
	libXcompshad.so.3 => /usr/lib64/libXcompshad.so.3 (0x00007fc1fb6c9000)
	libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00007fc1fb4be000)
	libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007fc1fb2b8000)
	libXfont.so.1 => /usr/lib64/libXfont.so.1 (0x00007fc1fb07b000)
	libXcomposite.so.1 => /usr/lib64/libXcomposite.so.1 (0x00007fc1fae78000)
	libXinerama.so.1 => /usr/lib64/libXinerama.so.1 (0x00007fc1fac75000)
	libXdmcp.so.6 => /usr/lib64/libXdmcp.so.6 (0x00007fc1faa6f000)
	libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007fc1fa85d000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fc1fa646000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc1fa2fb000)
	libXpm.so.4 => /usr/lib64/libXpm.so.4 (0x00007fc1fa0e9000)
	libxml2.so.2 => /usr/lib64/libxml2.so.2 (0x00007fc1f9d81000)
	libpixman-1.so.0 => /usr/lib64/libpixman-1.so.0 (0x00007fc1f9adb000)
	libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007fc1f9898000)
	libjpeg.so.8 => /usr/lib64/libjpeg.so.8 (0x00007fc1f962f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc1f9275000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc1f9057000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fc1f8ccf000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fc1f8ab8000)
	libXdamage.so.1 => /usr/lib64/libXdamage.so.1 (0x00007fc1f88b5000)
	libXrandr.so.2 => /usr/lib64/libXrandr.so.2 (0x00007fc1f86aa000)
	libXtst.so.6 => /usr/lib64/libXtst.so.6 (0x00007fc1f84a4000)
	libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007fc1f8206000)
	libfontenc.so.1 => /usr/lib64/libfontenc.so.1 (0x00007fc1f7ffe000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc1fc5e6000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc1f7dfa000)
	liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007fc1f7bbf000)
	libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00007fc1f79a2000)
opensuse-tumbleweed:~ # ldd /usr/lib64/libXcompshad.so.3
	linux-vdso.so.1 (0x00007ffe67dae000)
	libX11.so.6 => /usr/lib64/nx/X11/libX11.so.6 (0x00007f27254ee000)
	libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f27252dc000)
	libXdamage.so.1 => /usr/lib64/libXdamage.so.1 (0x00007f27250d9000)
	libXrandr.so.2 => /usr/lib64/libXrandr.so.2 (0x00007f2724ece000)
	libXtst.so.6 => /usr/lib64/libXtst.so.6 (0x00007f2724cc8000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f2724940000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f2724586000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f272436f000)
	libXcomp.so.3 => /usr/lib64/libXcomp.so.3 (0x00007f2724036000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2723e18000)
	libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00007f2723c0d000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f27238c2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2725a45000)
	libjpeg.so.8 => /usr/lib64/libjpeg.so.8 (0x00007f2723659000)
	libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007f2723416000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f27231ff000)
```

**Review by uli42 — CHANGES_REQUESTED** [review]
I'd prefer two changes:
- using DT_RUNPATH instead of DT_RPATH
- have the correct RUNPATH after manual compilation (pointing to the build dirs) and after make install (pointing to the installation dirs)

**Comment by Ionic** [comment]
Have implemented both points now.

Because we do not use the install target within `nx-X11/programs/Xserver`, I am instead creating a new binary `nxagent-relink` that includes the system RUNPATH and will be copied into the destroot from our main `Makefile`. The `nxagent` binary includes a build-time RUNPATH.

Example on Debian:

```
nxlibs@apgunner~/src/nx-libs-arctica-git(git)-[bugfix/rpath] %  readelf -d nx-X11/programs/Xserver/nxagent*

File: nx-X11/programs/Xserver/nxagent

Dynamic section at offset 0x44ebf8 contains 46 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXcomp.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXcompshad.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXrender.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXfixes.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXfont2.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libXcomposite.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXinerama.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXdmcp.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libNX_X11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXext.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXpm.so.4]
 0x0000000000000001 (NEEDED)             Shared library: [libxml2.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpixman-1.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpng12.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libjpeg.so.62]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../../exports/lib]
 [...]

File: nx-X11/programs/Xserver/nxagent-relink

Dynamic section at offset 0x44ebf8 contains 46 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXcomp.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXcompshad.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXrender.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXfixes.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXfont2.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libXcomposite.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXinerama.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXdmcp.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libNX_X11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXext.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXpm.so.4]
 0x0000000000000001 (NEEDED)             Shared library: [libxml2.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpixman-1.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpng12.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libjpeg.so.62]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [/usr/lib/x86_64-linux-gnu/nx/X11]
 [...]

nxlibs@apgunner~/src/nx-libs-arctica-git(git)-[bugfix/rpath] %  readelf -d $(which nxagent)

Dynamic section at offset 0x433bf8 contains 46 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXcomp.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXcompshad.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXrender.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXfixes.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXfont2.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libXcomposite.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXinerama.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXdmcp.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libNX_X11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXext.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXpm.so.4]
 0x0000000000000001 (NEEDED)             Shared library: [libxml2.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpixman-1.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpng16.so.16]
 0x0000000000000001 (NEEDED)             Shared library: [libjpeg.so.62]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [/usr/lib/x86_64-linux-gnu/nx/X11]
 [...]
```

Example on OpenSuSE Tumbleweed:

```
ionic@japsand ~ #  readelf -d /var/cache/obs-build/opensuse/tumbleweed/x86_64/home/abuild/rpmbuild/BUILD/nx-libs-3.5.99.12/nx-X11/programs/Xserver/nxagent

Dynamic section at offset 0x42fc78 contains 46 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXcomp.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXcompshad.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXrender.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXfixes.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXfont.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXcomposite.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXinerama.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXdmcp.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libNX_X11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXext.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXpm.so.4]
 0x0000000000000001 (NEEDED)             Shared library: [libxml2.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpixman-1.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpng16.so.16]
 0x0000000000000001 (NEEDED)             Shared library: [libjpeg.so.8]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../../exports/lib]
 [...]
ionic@opensuse-tumbleweed:~> readelf -d $(which nxagent)

Dynamic section at offset 0x42fc78 contains 46 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXcomp.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXcompshad.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXrender.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXfixes.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXfont.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXcomposite.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXinerama.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXdmcp.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libNX_X11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXext.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXpm.so.4]
 0x0000000000000001 (NEEDED)             Shared library: [libxml2.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpixman-1.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpng16.so.16]
 0x0000000000000001 (NEEDED)             Shared library: [libjpeg.so.8]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [/usr/lib64/nx/X11]
 [...]
```

**Comment by uli42** [comment]
Unfortunately this is not complete: there's no RPATH/RUNPATH in nxproxy.

**Comment by sunweaver** [comment]
On  Di 02 Jan 2018 22:07:41 CET, Ulrich Sibiller wrote:

> Unfortunately this is not complete: there's no RPATH/RUNPATH in nxproxy.

@uli42: @Ionic: Please note that we never had nxproxy/nxcomp link  
against libNX_X11.

We also include from X.org's headers in nxcomp, but do not link against it.


```
[mike@minobo nxcomp (bugfix/rpath)]$ grep -ri include src/*.cpp | grep X11
src/ClientChannel.cpp:#include <X11/X.h>
src/ClientChannel.cpp:#include <X11/Xatom.h>
src/Jpeg.cpp:#include <X11/Xmd.h>
src/Pgn.cpp:#include <X11/Xmd.h>
src/ServerChannel.cpp:#include <X11/X.h>
src/ServerChannel.cpp:#include <X11/Xatom.h>
```

The nxproxy build only links against nxcomp, neither against  
nxcompshad, nor libNX_X11.

So the question is: is  
https://github.com/ArcticaProject/nx-libs/pull/614/commits/1c1431c0ff41afa8221ea8a1e0d4514746ebbaa3 really necessary? IMHO  
not.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by Ionic** [comment]
Essentially copying what I wrote on IRC:

For `nxproxy`, not `libX11` (or `libNX_X11`) is the problem, but `libXcomp`.

During the build process, we build `libXcomp` and link it from `../nxcomp/src/.libs/libXcomp.so` (assuming `PWD` is `nxproxy/`).

Spawing the `nxproxy` binary directly wouldn't be possible if there was no prior `libXcomp.so` installed in system directories (since typically no `RPATH` is added by autotools).

We want to fix *that* issue, and to do so we have to:
  - use `libtool` as well, which:
    o creates wrapper scripts for binaries (with binaries in `./src/.libs/` and wrapper scripts in `./src/` in our case)
    o binaries in `./src/.libs/` have an `RPATH` set to `./src/.libs/` (which will be stripped upon installation)
    o wrapper scripts set `LD_LIBRARY_PATH` to the directories of all dependent libraries that are not available in system directories (i.e., have been linked using `-Lsomeotherdir`)
  - make sure that the binaries use `DT_RUNPATH` instead of `DT_RPATH`, since `DT_RPATH` overrides `LD_LIBRARY_PATH`, while for `DT_RUNPATH` the situation is reversed (`LD_LIBRARY_PATH` is searched first, then `DT_RUNPATH` if no matching library has been found)

We could trust libtool to "do the right thing" for the latter point, but I think that I've seen situations in which it wasn't "doing the right thing".

**Comment by Ionic** [comment]
Then again, it seems that in this special case `libtool` does not seem to add an `RPATH` automatically to the binary. Probably because we're not also building a library and linking that in the same project.

Enabling the new dtags to get `RUNPATH` instead of `RPATH` won't do any harm, though, even if there isn't any `RPATH`.

**Comment by uli42** [comment]
the latest version creates a shell script nxproxy/src/nxproxy and and binary nxproxy/src/.libs/lt-nxproxy with the correct installation RUNPATH. Looks ok to me.

**Comment by Ionic** [comment]
`lt-nxproxy` is not created on newer boxes, it seems and the `nxproxy` binary created in `nxproxy/src/.libs/` does not contain a `RUNPATH`. That's fine, though, I figure, since the shell script will correctly set `LD_LIBRARY_PATH`.

So what is generated seems to depend upon the autotools/libtool version used - but either should generate something usable.

The newer scheme might make it more difficult to run nxproxy out of the source tree with `gdb`, but [of course there's a handy way to do that as well](https://www.gnu.org/software/libtool/manual/html_node/Debugging-executables.html).

Merging.

**Pull request merged**
