### PR TITLE
Pr/fix clang warnings

### PR DESCRIPTION
**Pull request by uli42**
fix some of the warnings that occured in clang builds via Travis (https://travis-ci.org/ArcticaProject/nx-libs/jobs/481524533)

### CODE REVIEW

**Comment by sunweaver** [comment]
@uli42: unsure about this PR's status. Ready to merge from your side? Why did I not work on its review earlier? I remember I was asked to wait, but I am unsure now. Request for feedback.

**Comment by uli42** [comment]
Wanted to see Ionic reviewing it

Am Fr., 15. Feb. 2019, 12:02 hat Mike Gabriel <notifications@github.com>
geschrieben:

**Comment by sunweaver** [comment]
On  Fr 15 Feb 2019 14:39:57 CET, Ulrich Sibiller wrote:

> Wanted to see Ionic reviewing it
>

Ok.
Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
please merge, I doubt Ionic will ever check this

**Review by sunweaver — APPROVED** [review]
merging as requested (without much review, in fact)

**Pull request merged**
