### PR TITLE
pr/drop_libNX_Xext

### PR DESCRIPTION
**Pull request by uli42**
completely drop libNX_Xextby replacing it with the system's version. Please review!

### CODE REVIEW

**Comment by sunweaver** [comment]
@uli42: AWESOME!!!

Please rebase against latest 3.6.x if possible. Please use the same mail address for all commits, if possible and appropriate.

You have not removed libNX_Xext as a package from debian/\* and nx-libs.spec. Shall I propose a patch?

**Comment by sunweaver** [comment]
Once you have re-pushed changes...

```
git checkout 3.6.x
git pull origin 3.6.x
git checkout pr/drop_libNX_Xext
git rebase 3.6.x
git rebase -i HEAD~~~~~ ### -> change author / mail address
# deeply check once more...
git push git@github.com:uli42/nx-libs.git pr/drop_libNX_Xext:pr/drop_libNX_Xext
```

I will copy your branch, add packaging stuff and post the branch for cherry-picking. Those commits from me should then be pushed to your pr/drop_libNX_Xext branch for finally merging.

**Comment by uli42** [comment]
On Fri, Jul 1, 2016 at 1:22 PM, Mike Gabriel notifications@github.com wrote:

> @uli42: AWESOME!!!
> 
> Please rebase against latest 3.6.x if possible. Please use the same mail address for all commits, if possible and appropriate.
> 
> You have not removed libNX_Xext as a package from debian/\* and nx-libs.spec. Shall I propose a patch?

Yes, I was hoping so..

Uli

**Comment by uli42** [comment]
On Fri, Jul 1, 2016 at 1:28 PM, Mike Gabriel notifications@github.com wrote:

> Once you have re-pushed changes...
> 
> git checkout 3.6.x
> git pull origin 3.6.x
> git checkout pr/drop_libNX_Xext
> git rebase 3.6.x
> git rebase -i HEAD~~~~~ ### -> change author / mail address
> 
> # deeply check once more...
> 
> git push git@github.com:uli42/nx-libs.git pr/drop_libNX_Xext:pr/drop_libNX_Xext
> 
> I will copy your branch, add packaging stuff and post the branch for cherry-picking. Those commits from me should then be pushed to your pr/drop_libNX_Xext branch for finally merging.

Will take some time, have some other stuff to do right now. Did you test it?

**Comment by uli42** [comment]
ok, updated and rebased

**Comment by sunweaver** [comment]
Hi Uli,

On  Fr 01 Jul 2016 13:45:07 CEST, Ulrich Sibiller wrote:

> On Fri, Jul 1, 2016 at 1:28 PM, Mike Gabriel  
> notifications@github.com wrote:
> 
> > Once you have re-pushed changes...
> > 
> > git checkout 3.6.x
> > git pull origin 3.6.x
> > git checkout pr/drop_libNX_Xext
> > git rebase 3.6.x
> > git rebase -i HEAD~~~~~ ### -> change author / mail address
> > 
> > # deeply check once more...
> > 
> > git push git@github.com:uli42/nx-libs.git  
> > pr/drop_libNX_Xext:pr/drop_libNX_Xext
> > 
> > I will copy your branch, add packaging stuff and post the branch  
> > for cherry-picking. Those commits from me should then be pushed to  
> > your pr/drop_libNX_Xext branch for finally merging.
> 
> Will take some time, have some other stuff to do right now. Did you test it?

I am on it... Packaging files already in place...

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by sunweaver** [comment]
Hi Uli,

I have queued in this PR after the libXau-cleanup PR. Here is my branch containing some fixups and packaging stuff:
https://github.com/sunweaver/nx-libs/tree/pr/drop_libNX_Xext

It feels that you should merge my commits into your libNX_Xext full removal commit and push back to your PR branch.

Doing some more testing regarding functionality.

Mike

**Comment by uli42** [comment]
Again my limited git knowledge falls on my feet. I cannot merge you commits:

```
$ git merge sunweaver/pr/drop_libNX_Xext
error: The following untracked working tree files would be overwritten by merge:
        nx-X11/lib/X11/AuDispose.c
        nx-X11/lib/X11/AuFileName.c
        nx-X11/lib/X11/AuGetBest.c
        nx-X11/lib/X11/AuRead.c
```

I don't get it. These files are neither in my tree nor in your tree

**Comment by uli42** [comment]
Integrated sunweavers patches

**Pull request merged**
