### PR TITLE
render: picture.c avoid use of uninitialised values

### PR DESCRIPTION
**Pull request by sunweaver**
This is WIP, PR filed for documentation purposes only...

This PR attempts fixing #325...

### CODE REVIEW

**Comment by Ionic** [comment]
Mh, that conflicts with my render update, but I guess it doesn't make a big difference the update isn't fully working anyway, at least currently.

**Comment by sunweaver** [comment]
Hi Ionic

On Tue Feb 14 21:17:50 2017 GMT+0100, Mihai Moldovan wrote:
> Mh, that conflicts with my render update, but I guess it doesn't make a big difference the update isn't fully working anyway, at least currently. 

My question regarding your work on the Render extension is: would it make sense to backport individual commits already? Esp those not directly related to files in Xserver/render/

???
Mike 
-- 
Sent from my Fairphone (running Sailfish OS)...

**Comment by Ionic** [comment]
Not really, I've tried to keep it render-centric as much as possible, only changing other parts when absolutely necessary. It's highly inter-dependent and will likely just fall apart if you pick separate commits instead of the full deal.

**Comment by sunweaver** [comment]
Will be superseded by #440. Thus, closing...

**Pull request closed without merging**
