### PR TITLE
Implement GitHub Actions

### PR DESCRIPTION
**Pull request by mjtrangoni**
Hi @sunweaver, @uli42 

as Travis-CI is moving to a freemium model, I am deprecating it in favor of GitHub Actions.

Currently it runs builds with **gcc** and **clang** for the following Linux distros,

1. Ubuntu 16.04
2. Ubuntu 20.04
3. Debian Stable
4. Debian SID
5. CentOS 7
6. CentOS 8
7. Fedora Latest

It also builds on **Ubuntu 20.04** and **gcc** on different architectures, thanks to [this Action](https://github.com/marketplace/actions/run-on-architecture),

1. armv7
2. aarch64
3. ppc64le
4. s390x

And the following linters,

1. [shellcheck](https://github.com/koalaman/shellcheck)
2. [pylint](https://pylint.org/)
3. [cppcheck](https://github.com/danmar/cppcheck)
4. [PVS-Studio Analyzer](https://www.viva64.com/en/pvs-studio/)

Best regards,

Mario

### CODE REVIEW

**Comment by sunweaver** [comment]
@mjtrangoni what is the status of this PR? I saw you removed the W-I-P tag. Go ahead and merge?

**Comment by sunweaver** [comment]
@mjtrangoni btw, the i386 build failures should now be fixed.

**Comment by mjtrangoni** [comment]
@sunweaver no, I still need to fix some build which are failing with CLANG. If you want to take a look what I am missing, you can.

About i386, I already talked to @uli42 about it. Need to check if Actions support this.

**Comment by uli42** [comment]
@Mario Trangoni <mjtrangoni@gmail.com> I have sent you an email with some
fixing ideas a few days ago - have you checked that?

**Comment by mjtrangoni** [comment]
@uli42 yes, but didnt have the time for looking at it

**Comment by mjtrangoni** [comment]
@sunweaver ready to merge after #1001. Thanks!

**Comment by mjtrangoni** [comment]
@sunweaver any update?

**Review by sunweaver — APPROVED** [review]
Sorry for the long delay. Thanks for the switch over.

**Pull request merged**
