### PR TITLE
Pr/fix xkb crash

### PR DESCRIPTION
**Pull request by uli42**

### CODE REVIEW

**Comment by uli42** [comment]
Robert Kudyba has tested this PR and confirmed the crashes described in #808 are gone!

**Review by sunweaver — APPROVED** [review]
LGTM

**Comment by sunweaver** [comment]
@uli42: It seems like the patches from this PR should make its way into nx-libs in Debian buster, right? Please confirm.

**Comment by uli42** [comment]
On Tue, May 21, 2019 at 11:25 AM Mike Gabriel <notifications@github.com> wrote:
>
> @uli42: It seems like the patches from this PR should make its way into nx-libs in Debian buster, right? Please confirm.


Well, yes. But that's valid for all fixes...

Uli

**Pull request merged**
