### PR TITLE
Fix shellcheck issues

### PR DESCRIPTION
**Pull request by mjtrangoni**
Hi @sunweaver @uli42,

I fixed some shellcheck issues here, as I am working on integrating this tool to GitHub actions.

PTAL and test it!

Best regards,

Mario

### CODE REVIEW

**Review by sunweaver — APPROVED** [review]
Thanks!

**Comment by mjtrangoni** [comment]
@sunweaver @uli42 I realized now there are commits from you here. I am confused.

**Comment by uli42** [comment]
Yes, it is a bit strange. It looks, like the merge commit got lost somehow.
Showing current HEAD with tig hides it.

**Comment by sunweaver** [comment]
Sigh, you are right. Something must have gone wrong while rebasing (and force-pushing the rebased branch to the PR update branch). Sorry for that. The shell fixes are in the code, so we have to live with this now. Right?

**Comment by uli42** [comment]
I guess so.

**Pull request merged**
