### PR TITLE
XRender - remove duplicate code

### PR DESCRIPTION
**Pull request by mikedep333**
This PR was split off from #35 

As explained in PR #29, there is duplicate XRender code. Much of it appears to be unused.

This PR is to cleanup the unused code.

I still need to check whether the duplicate headers can be removed (or at least replaced with a symlink.)

### CODE REVIEW

**Comment by sunweaver** [comment]
@mikedep333, @Ionic: We have to be careful with such code removals.

What is happening in nxagent is that parts of the xserver code require modifications for nxagent, so complete files from the xorg-server code tree  get duplicated (like e.g., render.c).

When it comes to rebasing the nxagent pseudo-hw driver against latest xorg-server code, we have to completely rebase those duplicted NX*.{c|h} files against what we find in the original files (in Xserver/render, Xserver/dix, etc.).

The X.Org team broke ABI at several places (esp. in the dix/ code) within the xorg-server code tree.  Thus, I wonder if we rather should approach this like given below:
- isolate functions that have NX-specific changes
- ship _those_ functions in NX*.{c|h} (they may need rebasing later when it comes to compiling nxagent against latest X.Org Xserver code)
- leave the original files intact (render/_.{c|h}, dix/_.{c|h}, etc.) and actually use them in hw/nxagent/
- make sure the functions/symbols in NX*.{c|h} are an overlay replacing specific functions shipped in the original X.Org code files (I guess it requires a precise re-arranging of the #include headers)

Comments? Feedback?

**Comment by sunweaver** [comment]
And... the .h files cannot be removed without hassle, as they are also used inside the xorg-server code tree itself:

```
gcc -c -g -O3 -fno-strict-aliasing -ansi -Wall -Wpointer-arith -Wundef    -I. -I../include -I../../../exports/include/X11 -I../../../include/extensions           -I../../../programs/Xserver/Xext -I../../../programs/Xserver/render         -I../../../lib/Xau  -I../../../../nxcomp  -I../../.. -I../../../exports/include   -Dlinux -D__amd64__ -D_POSIX_C_SOURCE=199309L               -D_POSIX_SOURCE -D_XOPEN_SOURCE                 -D_BSD_SOURCE -D_SVID_SOURCE                                 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64              -D_GNU_SOURCE               -DSHAPE -DXINPUT -DXKB -DXAPPGROUP     -DXCSECURITY -DTOGCUP   -DXF86BIGFONT -DDPMSExtension   -DPANORAMIX      -DRENDER -DRANDR   -DXFIXES -DDAMAGE -DCOMPOSITE -DXEVIE    -DGCCUSESGAS -DAVOID_GLYPHBLT -DPIXPRIV -DSINGLEDEPTH              -DXFreeXDGA -DXvExtension            -DXFree86Server                -DXF86VIDMODE               -DXvMCExtension         -DSMART_SCHEDULE                -DBUILDDEBUG -DXResExtension                -DX_BYTE_ORDER=X_LITTLE_ENDIAN              -DXORG_VERSION_CURRENT="(((6) * 10000000) + ((9) * 100000) + ((0) * 1000) + 0)" -D_XSERVER64 -DNDEBUG   -DFUNCPROTO=15 -DNARROWPROTO   -DXSERV_t -DTRANS_SERVER -DUNIXCONN -DTCPCONN -DHAS_STICKY_DIR_BIT -DHAS_FCHOWN -DIPv6         -DHASXDMAUTH -DSECURE_RPC  -DDDXOSINIT -DSERVER_LOCK -DDDXOSFATALERROR                -DDDXOSVERRORF -DDDXTIME           -DUSE_RGB_TXT           -DBUILDERADDR='"xorg@lists.freedesktop.org"' -DFAIL_HARD -DNX_TRANS_SOCKET                     -DNX_TRANS_AUTH                       -DNX_TRANS_FOPEN                      -DNX_TRANS_SLEEP                      -DNX_TRANS_EXIT                       -DNX_TRANS_WAKEUP=1000  -DXDMCP -DMITMISC -DXTEST -DXTRAP     -DXSYNC -DXCMISC -DXRECORD  -DMITSHM -DBIGREQS -DXF86VIDMODE    -DXF86MISC -DDBE -DDPMSExtension -DEVI   -DXV -DXVMC    -DGLXEXT -D__GLX_ALIGN64           -DRES   utils.c
utils.c:147:21: fatal error: picture.h: No such file or directory
 #include "picture.h"
                     ^
compilation terminated.
```

This actually let's the above proposed approach appear even more sane and clean. Right?

**Comment by sunweaver** [comment]
About .h files removal... We surely don't want to include files from hw/nxagent in any .c file in the original Xserver code tree.

**Comment by uli42** [comment]
Looking at the code of 3.5.x you can see that a lot of duplicated/derived files are starting with lines like these:

#ifdef NXAGENT_UPGRADE

#include "X/&lt;same filename&gt;"

#else

... &lt;original X code&gt;

The file X/&lt;same filename&gt; contains another code duplication. So it seems to me like this code isolation sunweaver is proposing had already been made in the original code but got lost during the transition to 3.6.x.

**Comment by sunweaver** [comment]
On  Di 26 Mai 2015 13:23:10 CEST, uli42 wrote:

> Looking at the code of 3.5.x you can see that a lot of  
> duplicated/derived files are starting with lines like these:
> 
> #ifdef NXAGENT_UPGRADE
> 
> #include "X/<same filename>"
> 
> #else
> 
> ... <original X code>
> 
> The file X/<same filename> contains another code duplication. So it  
> seems to me like this code isolation sunweaver is proposing had  
> already be made in the original code but got lost during the  
> transition to 3.6.x.

Actually not. The NXAGENT_UPGRADE definitions had been set to 1 always  
for recent versions of NX and nx-libs (our fork).

So, the upgraded code has always been used for a while. The code that  
was used with NXAGENT_UPGRADE=1 resided in the hw/nxagent/X/ subfolder  
(that you refer to).

We (Ionic, sunweaver) moved that code into hw/nxagent/ and dropped the  
NXAGENT_UPGRADE parameter (and the deprecated code that could still be  
built with setting NXAGENT_UPGRADE to undef). See [1].

[1] https://github.com/ArcticaProject/nx-libs/pull/11

## 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/freebusy/m.gabriel%40das-netzwerkteam.de.xfb

**Comment by Ionic** [comment]
> - make sure the functions/symbols in NX*.{c|h} are an overlay replacing specific functions shipped in the original X.Org code files (I guess it requires a precise re-arranging of the #include headers)

Hopefully that doesn't prove to be difficult. Remember that C does not support overloading or redefining functions.

**Comment by sunweaver** [comment]
> > - make sure the functions/symbols in NX*.{c|h} are an overlay
> >   replacing specific functions shipped in the original X.Org code files
> >   (I guess it requires a precise re-arranging of the #include headers)
> 
> Hopefully that doesn't prove to be difficult. Remember that C does not
> support overloading or redefining functions.

Are you sure it is not supported? See http://stackoverflow.com/questions/617554/override-a-function-call-in-c , for example.

**Comment by sunweaver** [comment]
> Hopefully that doesn't prove to be difficult. Remember that C does not
> support overloading or redefining functions.

Or here: http://stackoverflow.com/questions/19023018/overriding-c-library-functions-calling-original

**Comment by mikedep333** [comment]
Hi guys,

You seem to be much more knowledgeable about this topic than I am, so I will let you decide how to handle this PR.

**Comment by sunweaver** [comment]
I mark this PR as invalid for now, because the solution requires to be different.

The copies of code in the nxagent DDX should be minimized to the passages that got changed compared to the files shipped in the traditional Xserver code.

I will propose new patches via the branch that is used for this PR, so we will revive this PR in some hours, I guess.

**Comment by sunweaver** [comment]
This PR has will be obsoleted by my next PR coming soon.

Patch preview, one amongst many:
https://github.com/sunweaver/nx-libs/commit/257bf7e552b072bfe4f98ae94a0fbc371cd6afa4

**Pull request closed without merging**
