### PR TITLE
nxagentReversePointerMap: Don't assume Xevent.xbutton.button is alway…

### PR DESCRIPTION
**Pull request by sunweaver**
…s greater than zero. We have seen Xevent.xbutton.button being set to AnyButton (equaling 0).

Fixes ArcticaProject/nx-libs#92
Fixes X2GoBTS#791

### CODE REVIEW

**Comment by sunweaver** [comment]
@opoplawski: I finally got to looking into issue ArcticaProject/nx-libs#92 (X2GoBTS#791). Do you have time and resources to review my change? Thanks in advance.

**Comment by uli42** [comment]
I don't now about that ReversePointerMap but your change uses another offset now. Is this really equivalent?

**Comment by sunweaver** [comment]
The offset is changed everywhere in nxagent afaict. Don't you think? The nxagentReversePointerMap is an internal mapping between nxagent's "buttons" and the underlying Xserver's "buttons". I changed the offset at all occurring locations.

**Comment by uli42** [comment]
On Mon, Jun 13, 2016 at 1:20 PM, Mike Gabriel notifications@github.com wrote:

> The offset is changed everywhere in nxagent afaict. Don't you think? The nxagentReversePointerMap is an internal mapping between nxagent's "buttons" and the underlying Xserver's "buttons". I changed the offset at all occurring locations.

Right, I have overlooked that you also changed the part where data is
actually written.

BTW: I have not been aware of this bug. But I occassionally have seen
exactly this crash when trying to debug issue #118

**Comment by sunweaver** [comment]
Hi Uli,

On Mon Jun 13 13:35:09 2016 GMT+0200, Ulrich Sibiller wrote:

> On Mon, Jun 13, 2016 at 1:20 PM, Mike Gabriel notifications@github.com wrote:
> 
> > The offset is changed everywhere in nxagent afaict. Don't you think? The nxagentReversePointerMap is an internal mapping between nxagent's "buttons" and the underlying Xserver's "buttons". I changed the offset at all occurring locations.
> 
> Right, I have overlooked that you also changed the part where data is
> actually written.
> 
> BTW: I have not been aware of this bug. But I occassionally have seen
> exactly this crash when trying to debug issue #118
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.￼
> Assuming this is an approval?
> Mike

## 

Sent from my Jolla

**Comment by uli42** [comment]
yes, this is an approval

**Pull request merged**
