### PR TITLE
Pr/drop ipaq

### PR DESCRIPTION
**Pull request by uli42**

### CODE REVIEW

**Comment by sunweaver** [comment]
What the heck is "Ipaq"?

**Comment by uli42** [comment]
https://en.wikipedia.org/wiki/IPAQ

**Comment by sunweaver** [comment]
On  Do 27 Jun 2019 22:34:24 CEST, Ulrich Sibiller wrote:

> https://en.wikipedia.org/wiki/IPAQ

WoW. Yeah, we can safely remove support for that.

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4351) 486 14 27

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Review by sunweaver — APPROVED** [review]
LGTM

**Pull request merged**
