### PR TITLE
Pr/lib nx x11 defines

### PR DESCRIPTION
**Pull request by uli42**
fix some of the missing defines in libNX_X11

### CODE REVIEW

**Comment by uli42** [comment]
Please do not merge for now, I think I must redo this. My patches add the defines to config.h while the configure.ac from xorg upstream's libxtrans states it must be a cflag define. Unsure why.

**Comment by sunweaver** [comment]
@uli42: do you want all commits to be not merged? It seems that some commits would be ok to merge.

**Comment by uli42** [comment]
No, please do not merge any of them

**Review by sunweaver — APPROVED** [review]
LGTM

**Comment by uli42** [comment]
As I have stated above please do not merge any of them!

Mike Gabriel <notifications@github.com> schrieb am Sa., 17. Okt. 2020,
22:03:

**Comment by uli42** [comment]
Well, after thinking again it might be ok, it's better than doing nothing
here

Ulrich Sibiller <uli42@gmx.de> schrieb am Sa., 17. Okt. 2020, 22:22:

**Comment by sunweaver** [comment]
On  Sa 17 Okt 2020 22:25:17 CEST, Ulrich Sibiller wrote:

> Well, after thinking again it might be ok, it's better than doing nothing
> here

Ouch, I missed that comment.

Let's see what bells ring once people start testing this merged code, then...

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler Str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4351) 850 8940

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Pull request merged**
