### PR TITLE
Pr/add lib x11 links

### PR DESCRIPTION
**Pull request by uli42**
Fix for #234

### CODE REVIEW

**Comment by sunweaver** [comment]
@uli42: please rebase #248 again against latest 3.6.x HEAD. This PR is the next to be merged.

**Review by sunweaver — APPROVED** [review]
LGTM... Before merging, I will test-build this and check if what the code promises really happens. But apart from that, I am fine with that change.

Please make sure the open issue that gets addressed by this fix, gets closed via the commit msg. Thanks.

**Comment by uli42** [comment]
rebased

**Review by sunweaver — CHANGES_REQUESTED** [review]
@uli42: please merge the two ks_tables.h related commits into one (we don't want flawed commits in the Git log). Requesting more changes.

Let's merge pr/unused_files first, please.

**Review by sunweaver — APPROVED** [review]

**Pull request merged**
