### PR TITLE
prematurely abort ProcSendEvent if a ClientMsg has been fordwarded

### LINKED ISSUE #1065: Rootless mode: Qt applications do not exit
This looks like a Qt bug, but since it only happens with `nxagent -R` and not with `nxagent`, I would like to discuss it here before reporting the issue to the Qt organisation.

What is happening? It seems Qt applications work fine with nxagent as a nested X server, with or without the `-R` (rootless) option... until they need to exit, at which point their windows disappear but the process seems to hang, possibly waiting for something from nxagent.

How to reproduce?
- Launch NXAGENT (tested with version 3.5.99.27):  run e.g. `nxagent -ac -R :222`
- Get a Qt application. I encountered the issue with quiterss, rssguard and featherpad but suggest to use a dead simple, "Hello World"-like Qt application for this purpose:
```console
# apt install -y build-essential qtbase5-dev # assuming Debian here
$ mkdir qtdeadsimple
$ cd qtdeadsimple
$ cat > main.cpp <<EOF
#include <QApplication>
#include <QPushButton>
int main(int argc, char **argv) {
        QApplication app(argc, argv);
        QPushButton *button = new QPushButton("hello");
        QPushButton::connect(button, SIGNAL(clicked(bool)), &app, SLOT(quit()));
        button->show();
        return app.exec();
}
EOF
$ qmake -project "QT += widgets"
$ qmake
$ make
$ env -i DISPLAY=:222 ./qtdeadsimple
```

A small "hello" button should appear. Clicking it is supposed to make the application exit. It works fine in normal mode but in rootless mode, the process will not exit.

The application outputs some warnings on stderr right after it starts (and long before it even tries to exit). So far there is no reason to believe they are related with this issue.
```
qt.qpa.xcb: X server does not support XInput 2
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-username'
qt.qpa.gl: QXcbConnection: Failed to initialize GLX
qt.qpa.xcb: QXcbConnection: XCB error: 1 (BadRequest), sequence: 169, resource id: 553, major code: 130 (Unknown), minor code: 47
```
A brief inspection of the stacks hints that thread 1 is waiting for thread 2 and thread 2 is waiting for something from the X server:
<details>
  <summary>Backtrace for thread 1</summary>

```
(gdb) bt 
#0 __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55fd549cb500) at ./nptl/futex-internal.c:57 
#1 __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55fd549cb500, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) 
 at ./nptl/futex-internal.c:87 
#2 0x00007fc6d9ea31bb in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55fd549cb500, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) 
 at ./nptl/futex-internal.c:139 
#3 0x00007fc6d9ea5818 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55fd549cb4b0, cond=0x55fd549cb4d8) at ./nptl/pthread_cond_wait.c:503 
#4 ___pthread_cond_wait (cond=0x55fd549cb4d8, mutex=0x55fd549cb4b0) at ./nptl/pthread_cond_wait.c:618 
#5 0x00007fc6da4dfbfb in QWaitConditionPrivate::wait (deadline=..., this=0x55fd549cb4b0) at thread/qwaitcondition_unix.cpp:146 
#6 QWaitCondition::wait (this=this@entry=0x55fd549d59d8, mutex=mutex@entry=0x55fd549d59b8, deadline=...) at thread/qwaitcondition_unix.cpp:225 
#7 0x00007fc6da4d9cf9 in QThread::wait (this=this@entry=0x55fd549cc680, deadline=...) at ../../include/QtCore/../../src/corelib/thread/qmutex.h:270 
#8 0x00007fc6d6ceceb9 in QXcbEventQueue::~QXcbEventQueue (this=0x55fd549cc680, __in_chrg=<optimized out>) at ./src/plugins/platforms/xcb/qxcbeventqueue.cpp:105 
#9 0x00007fc6d6cecf19 in QXcbEventQueue::~QXcbEventQueue (this=0x55fd549cc680, __in_chrg=<optimized out>) at ./src/plugins/platforms/xcb/qxcbeventqueue.cpp:116 
#10 0x00007fc6d6cc82f5 in QXcbConnection::~QXcbConnection (this=0x55fd549e0770, __in_chrg=<optimized out>) at ./src/plugins/platforms/xcb/qxcbconnection.cpp:143 
#11 0x00007fc6d6cc8b49 in QXcbConnection::~QXcbConnection (this=0x55fd549e0770, __in_chrg=<optimized out>) at ./src/plugins/platforms/xcb/qxcbconnection.cpp:155 
#12 0x00007fc6d6cc97be in qDeleteAll<QList<QXcbConnection*>::const_iterator> (end=..., begin=...) at ../../../../include/QtCore/../../src/corelib/tools/qalgorithms.h:320 
#13 qDeleteAll<QList<QXcbConnection*> > (c=...) at ../../../../include/QtCore/../../src/corelib/tools/qalgorithms.h:328 
#14 QXcbIntegration::~QXcbIntegration (this=0x55fd549d5d60, __in_chrg=<optimized out>) at ./src/plugins/platforms/xcb/qxcbintegration.cpp:227 
#15 0x00007fc6d6cc98b9 in QXcbIntegration::~QXcbIntegration (this=0x55fd549d5d60, __in_chrg=<optimized out>) at ./src/plugins/platforms/xcb/qxcbintegration.cpp:229 
#16 0x00007fc6d9731027 in QGuiApplicationPrivate::~QGuiApplicationPrivate (this=0x55fd549cb9c0, __in_chrg=<optimized out>) at kernel/qguiapplication.cpp:1724 
#17 0x00007fc6dab61859 in QApplicationPrivate::~QApplicationPrivate (this=0x55fd549cb9c0, __in_chrg=<optimized out>) at kernel/qapplication.cpp:163 
#18 0x000055fd53cc42f6 in main (argc=1, argv=0x7ffdbff8ebe8) at main.cpp:9 
```

</details>

<details>
<summary>Backtrace for thread 2</summary>

```
(gdb) thread 2 
[Switching to thread 2 (Thread 0x7fc6d60b96c0 (LWP 594953))]
(gdb) bt
#0 0x00007fc6d9f199ef in __GI___poll (fds=fds@entry=0x7fc6d60b8cc8, nfds=nfds@entry=1, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29 
#1 0x00007fc6d8e41d12 in poll (__timeout=-1, __nfds=1, __fds=0x7fc6d60b8cc8) at /usr/include/x86_64-linux-gnu/bits/poll2.h:47 
#2 _xcb_conn_wait (c=c@entry=0x55fd549e1f10, cond=cond@entry=0x55fd549e1f50, vector=vector@entry=0x0, count=count@entry=0x0) at ../../src/xcb_conn.c:508 
#3 0x00007fc6d8e4407a in xcb_wait_for_event (c=0x55fd549e1f10) at ../../src/xcb_in.c:703 
#4 0x00007fc6d6cec840 in QXcbEventQueue::run (this=0x55fd549cc680) at ./src/plugins/platforms/xcb/qxcbeventqueue.cpp:228 
#5 0x00007fc6da4d9ffd in operator() (__closure=<optimized out>) at thread/qthread_unix.cpp:351 
#6 (anonymous namespace)::terminate_on_exception<QThreadPrivate::start(void*)::<lambda()> > (t=...) at thread/qthread_unix.cpp:288 
#7 QThreadPrivate::start (arg=0x55fd549cc680) at thread/qthread_unix.cpp:311 
#8 0x00007fc6d9ea63ec in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444 
#9 0x00007fc6d9f26a1c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

</details>

Questions:
- Does this ring a bell?
- Have you encountered similar issues with client applications in the past?
- How would you further investigate the issue? Diving in Qt/XCB code? Inspecting X11 exchanges?

### PR DESCRIPTION
**Pull request by uli42**
Fixes ArcticaProject/nx-libs#1065

### CODE REVIEW

**Comment by sunweaver** [comment]
```
Events.c:4211:6: error: conflicting types for 'nxagentForwardRemoteExpose'; have 'void(void)'
7436
 4211 | void nxagentForwardRemoteExpose(void)
7437
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~
7438
Events.c:227:13: note: previous declaration of 'nxagentForwardRemoteExpose' with type 'int(void)'
7439
  227 | static Bool nxagentForwardRemoteExpose(void);
7440
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
7441
Events.c:227:13: warning: 'nxagentForwardRemoteExpose' used but never defined
7442
make[7]: *** [Makefile:575: Events.o] Error 1
```

@uli42 CI failure. Can you take a look? Thanks.

**Comment by uli42** [comment]
pushed a fixed version

**Comment by sunweaver** [comment]
Rebased and re-running CI...

**Comment by uli42** [comment]
https://github.com/ArcticaProject/nx-libs/issues/1015#issuecomment-2042661910
metions that there's Nullpointer check missing in
ForwardClientMessage. Maybe you can add one while at it...

**Review by sunweaver — APPROVED** [review]
Now, seems to work...

**Pull request merged**
