### PR TITLE
Feature/new xinerama randr 3.6.x

### PR DESCRIPTION
**Pull request by uli42**
I have re-implemented xinerama as outlined on the mailing list. This code does no more fake-xinerama but initializes xrandr (and therefore xinerama) properly. Everything is implemented in hw/nxagent.

TODO: track client side xrandr/xinerama changes and track window movement without resizing.

### CODE REVIEW

**Comment by sunweaver** [comment]
@uli42: oooppssss... I missed this PR completely. Will take a look today.

**Comment by sunweaver** [comment]
@uli42: I have rebased your changes on this branch. The rebased code can be found at https://github.com/sunweaver/nx-libs/tree/pr/xinerama-with-randr-in-nxagent.

Furthermore, I started commenting on the resulting patch/commit:
https://github.com/sunweaver/nx-libs/commit/0919215bd13e008d7c571deedbae90f1fac501a9#diff-1a28065cd3388a1bbb1941601c759cb8R3626

I have not tested the code (due to lack of a second display at the moment), but will do later today.

For the further reviewing workflow:
  (1) fetch the xinerama-with-randr-in-nxagent branch from https://github.com/sunweaver/nx-libs/.
  (2) force-push that branch to branch feature/new-xinerama-randr-3.6.x at https://github.com/uli42/nx-libs
  (3) add commits on top, if needed
  (4) wait for more feedback, make sure to highlight me via a comment or assign me (right column on the Github UI), so I get notified about changes
  (...) ...
  (n) At the very end, you will rebase all commits you maybe added on top of 0919215bd13e008d7c571deedbae90f1fac501a9 into one big commit (only if that makes sense for all commits, of course) and force-push to your feature/new-xinerama-randr-3.6.x branch again. Once that is done, I will merge into the 3.6.x branch.

**Comment by uli42** [comment]
I have issued that request just this night/morning...

Uli

----- Ursprüngliche Nachricht -----
Von: "Mike Gabriel" notifications@github.com
Gesendet: ‎12.‎05.‎2015 08:28
An: "ArcticaProject/nx-libs" nx-libs@noreply.github.com
Cc: "uli42" uli42@gmx.de
Betreff: Re: [nx-libs] Feature/new xinerama randr 3.6.x (#23)

@uli42: oooppssss... I missed this PR completely. Will take a look today.

**Comment by sunweaver** [comment]
@uli42: I tested your new code. Very good work.

The following use cases don't require any more looking at, it seems:
- rootless sessions
- fullscreen desktop sessions

-> those work fine.

 I see two remaining issues for windowed desktop sessions:
- moving the complete session window does not trigger a resize event
- if you resize a window using the left top (or bottom) corner of the NX desktop session window does, the intersecting does not work and the Xinerama border is too far to the left or too far on the right

Again, very good work! If you can take a look at the second aspect (wrong xinerama border when window resizing of the NX session window is done via the left window corners) and that gets fixed, I think we should consider merging your code (even if no resize event arrives in the session window after the window has been moved).

**Comment by uli42** [comment]
Sorry, I do not understand the stuff about force-pushing. I think you mean I should change my branch so that it reflects your pr/xinerama-with-randr-in-nxagent branch. I can fetch your branch. I can also merge your branch but then I have that merging commit in the history. I can also change to your branch and make a force-push to my branch but that does not work out. It just keeps telling me "everything is up-to-date". So what to do?

**Comment by uli42** [comment]
I know about that movement issue but I do not have a solution currently. I am getting the move event (a ConfigureNotify event) but the nx code actively prevents calling nxagentChangeScreenConfig in this case. If I force calling it the change triggers a ConfigureNotify again. And again. And so on. An endless loop. I first must understand why nx is acting that way. The problematic part is in hw/nxagent/Events.c nxagentHandleConfigureNotify in line 3460ff.

Regarding the "resize on the left corners" issue: I cannot reproduce it with Ubuntu 14.04 running Unity Desktop (with compiz as window manager). It works absolutely flawless in both single nxagent run and complete x2go session. So this looks like a window manager issue on your side. What window manager are you using?

**Comment by Ionic** [comment]
On 13.05.2015 10:53 PM, uli42 wrote:

> Sorry, I do not understand the stuff about force-pushing. I think you mean I
> should change my branch so that it reflects your
> pr/xinerama-with-randr-in-nxagent branch. I can fetch your branch. I can also
> merge your branch but then I have that merging commit in the history. I can also
> change to your branch man make a force-push to my branch but that does not work
> out. It just keeps telling me "everything is up-to-date". So what to do?

Do you still have that merge commit in your history, or have you reset to the
previous state without a merge commit?

Generally, all you have to do (from the previous state):

```
git checkout YOUR_BRANCH (if you're not already on it)
git fetch
git rebase origin/3.6.x
git push -f
```

(You may need to replace origin with your real remote name, if that should differ.)

Mihai

**Comment by uli42** [comment]
On Wed, May 13, 2015 at 11:12 PM, Mihai Moldovan
notifications@github.com wrote:

> On 13.05.2015 10:53 PM, uli42 wrote:
> 
> > Sorry, I do not understand the stuff about force-pushing. I think you mean I
> > should change my branch so that it reflects your
> > pr/xinerama-with-randr-in-nxagent branch. I can fetch your branch. I can also
> > merge your branch but then I have that merging commit in the history. I can also
> > change to your branch man make a force-push to my branch but that does not work
> > out. It just keeps telling me "everything is up-to-date". So what to do?
> 
> Do you still have that merge commit in your history, or have you reset to the
> previous state without a merge commit?

I have the previous one and removed the merge commit.

> Generally, all you have to do (from the previous state):
> 
> git checkout YOUR_BRANCH (if you're not already on it)
> git fetch
> git rebase origin/3.6.x

I tried git rebase sunweaver/pr/xinerama-with-randr-in-nxagent
(sunwwaver is my remote name for that repo) and ran into 2 conflicts:

First, rewinding head to replay your work on top of it...
Applying: first working version with server-side xinerama handling
without LD_LIBRARY_PATH
Applying: cleanup, no xinerama in rooless sessions
Applying: code cleanup; reformatting
Applying: remove trailing whitespace
Applying: use window geometry as provided by nxagentOptions structure
Applying: library clean-up: Don't build libNX_Xinerama anymore. Use
system's libXinerama shared library.
Using index info to reconstruct a base tree...
M    Makefile
M    debian/control
A    debian/libnx-xinerama-dev.install.in
A    debian/libnx-xinerama1.install.in
A    debian/libnx-xinerama1.postinst.in
A    debian/libnx-xinerama1.prerm
A    debian/libnx-xinerama1.symbols
M    debian/nx-x11-common.install
A    debian/nx-x11proto-xinerama-dev.install.in
M    debian/rules
M    nx-X11/config/cf/X11.tmpl
M    nx-X11/include/extensions/Imakefile
A    nx-X11/include/extensions/panoramiXext.h
A    nx-X11/include/extensions/panoramiXproto.h
M    nx-X11/lib/Imakefile
A    nx-X11/lib/Xinerama/Imakefile
A    nx-X11/lib/Xinerama/Xinerama-def.cpp
A    nx-X11/lib/Xinerama/Xinerama.c
M    nx-X11/programs/Xserver/Imakefile
M    nx-X11/programs/Xserver/Xext/panoramiX.h
M    nx-libs.spec
Falling back to patching base and 3-way merge...
CONFLICT (rename/delete):
nx-X11/programs/Xserver/randr/panoramiXproto.h deleted in library
clean-up: Don't build libNX_Xinerama anymore. Use system's libXinerama
shared library. and renamed in HEAD. Version HEAD of
nx-X11/programs/Xserver/randr/panoramiXproto.h left in tree.
CONFLICT (rename/delete): nx-X11/programs/Xserver/Xext/dpmsstubs.c
deleted in library clean-up: Don't build libNX_Xinerama anymore. Use
system's libXinerama shared library. and renamed in HEAD. Version HEAD
of nx-X11/programs/Xserver/Xext/dpmsstubs.c left in tree.
Failed to merge in the changes.
Patch failed at 0006 library clean-up: Don't build libNX_Xinerama
anymore. Use system's libXinerama shared library.
The copy of the patch that failed is found in:
   /home/uli/work/nx/ArcticaProject/nx-libs/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

> git push -f
> 
> (You may need to replace origin with your real remote name, if that should differ.)

I think I still do not understand why I should do this at all. Why not
leave it as is and develop on top of my branch until I am finished?

Uli

**Comment by sunweaver** [comment]
On  Mi 13 Mai 2015 23:42:25 CEST, uli42 wrote:

> > git push -f
> > 
> > (You may need to replace origin with your real remote name, if that  
> > should differ.)
> 
> I think I still do not understand why I should do this at all. Why not
> leave it as is and develop on top of my branch until I am finished?

@uli42: The force pushing needs to be done directly before the merge,  
so that there is one / only a few clean commit(s) at the end that we  
merge into 3.6.x branch. Please continue development as is and I will  
guide you through the Git stuff (or handle it myself) later on.

## 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/freebusy/m.gabriel%40das-netzwerkteam.de.xfb

**Comment by sunweaver** [comment]
On  Mi 13 Mai 2015 23:08:36 CEST, uli42 wrote:

> I know about that movement issue but I do not have a solution  
> currently. I am getting the move event (a ConfigureNotify event) but  
> the nx code actively prevents calling nxagentChangeScreenConfig in  
> this case. If I force calling it the change triggers a  
> ConfigureNotify again. And again. And so on. An endless loop. I  
> first must understand why nx is acting that way. The problematic  
> part is in hw/nxagent/Events.c nxagentHandleConfigureNotify in line  
> 3460ff.

I will take a short look at that later today. (I am currently faced  
with two deadlines coming close, so not much time here before the  
weekend).

> Regarding the "resize on the left corners" issue: I cannot reproduce  
> it with Ubuntu 14.04 running Unity Desktop (with compiz as window  
> manager). It works absolutely flawless in both single nxagent run  
> and complete x2go session. So this looks like a window manager issue  
> on your side. What window manager are you using?

The marco window manager shipped with MATE desktop. The marco window  
manager is a metacity fork IIRC.

## 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/freebusy/m.gabriel%40das-netzwerkteam.de.xfb

**Comment by uli42** [comment]
On Thu, May 14, 2015 at 5:28 AM, Mike Gabriel notifications@github.com wrote:

> On Mi 13 Mai 2015 23:08:36 CEST, uli42 wrote:
> 
> > I know about that movement issue but I do not have a solution
> > currently. I am getting the move event (a ConfigureNotify event) but
> > the nx code actively prevents calling nxagentChangeScreenConfig in
> > this case. If I force calling it the change triggers a
> > ConfigureNotify again. And again. And so on. An endless loop. I
> > first must understand why nx is acting that way. The problematic
> > part is in hw/nxagent/Events.c nxagentHandleConfigureNotify in line
> > 3460ff.
> 
> I will take a short look at that later today. (I am currently faced
> with two deadlines coming close, so not much time here before the
> weekend).

I have managed to fix that now
(https://github.com/uli42/nx-libs/commit/61018cd39d02fbda1f2f766d8320c53866fa55d3).
Please also have a look at my most current commit
https://github.com/uli42/nx-libs/commit/ae8230ce3add2f62b4d8a294fb9a375a6e530ed4.

> > Regarding the "resize on the left corners" issue: I cannot reproduce
> > it with Ubuntu 14.04 running Unity Desktop (with compiz as window
> > manager). It works absolutely flawless in both single nxagent run
> > and complete x2go session. So this looks like a window manager issue
> > on your side. What window manager are you using?
> 
> The marco window manager shipped with MATE desktop. The marco window
> manager is a metacity fork IIRC.

Oh, I have never heard about marco. Can you reproduce the issue with another WM?

Uli

**Comment by sunweaver** [comment]
On  Fr 15 Mai 2015 02:00:05 CEST, uli42 wrote:

> On Thu, May 14, 2015 at 5:28 AM, Mike Gabriel  
> notifications@github.com wrote:
> 
> > On Mi 13 Mai 2015 23:08:36 CEST, uli42 wrote:
> > 
> > > I know about that movement issue but I do not have a solution
> > > currently. I am getting the move event (a ConfigureNotify event) but
> > > the nx code actively prevents calling nxagentChangeScreenConfig in
> > > this case. If I force calling it the change triggers a
> > > ConfigureNotify again. And again. And so on. An endless loop. I
> > > first must understand why nx is acting that way. The problematic
> > > part is in hw/nxagent/Events.c nxagentHandleConfigureNotify in line
> > > 3460ff.
> > 
> > I will take a short look at that later today. (I am currently faced
> > with two deadlines coming close, so not much time here before the
> > weekend).
> 
> I have managed to fix that now
> (https://github.com/uli42/nx-libs/commit/61018cd39d02fbda1f2f766d8320c53866fa55d3).

Cool. Will test that later today when at uni.

> Please also have a look at my most current commit
> https://github.com/uli42/nx-libs/commit/ae8230ce3add2f62b4d8a294fb9a375a6e530ed4.

I am not sure that I understand this commit by just looking at the  
patch. Need to re-read it later.

> > > Regarding the "resize on the left corners" issue: I cannot reproduce
> > > it with Ubuntu 14.04 running Unity Desktop (with compiz as window
> > > manager). It works absolutely flawless in both single nxagent run
> > > and complete x2go session. So this looks like a window manager issue
> > > on your side. What window manager are you using?
> > 
> > The marco window manager shipped with MATE desktop. The marco window
> > manager is a metacity fork IIRC.
> 
> Oh, I have never heard about marco. Can you reproduce the issue with  
> another WM?

## I will check with another WM today, too.

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/freebusy/m.gabriel%40das-netzwerkteam.de.xfb

**Comment by uli42** [comment]
Am 15.05.2015 07:09 schrieb "Mike Gabriel" notifications@github.com:

> > I have managed to fix that now
> > (
> > https://github.com/uli42/nx-libs/commit/61018cd39d02fbda1f2f766d8320c53866fa55d3
> > ).
> 
> Cool. Will test that later today when at uni.

At uni? I had thought you are running a business... :-)

> > Please also have a look at my most current commit
> > 
> > https://github.com/uli42/nx-libs/commit/ae8230ce3add2f62b4d8a294fb9a375a6e530ed4
> > .
> 
> I am not sure that I understand this commit by just looking at the
> patch. Need to re-read it later.

No need to reread, this was just tell you there's a newer commit already.

> > > > Regarding the "resize on the left corners" issue: I cannot reproduce
> > > > it with Ubuntu 14.04 running Unity Desktop (with compiz as window
> > > > manager). It works absolutely flawless in both single nxagent run
> > > > and complete x2go session. So this looks like a window manager issue
> > > > on your side. What window manager are you using?
> > > 
> > > The marco window manager shipped with MATE desktop. The marco window
> > > manager is a metacity fork IIRC.
> > 
> > Oh, I have never heard about marco. Can you reproduce the issue with
> > another WM?
> 
> I will check with another WM today, too.

OK.

Uli

**Comment by sunweaver** [comment]
On  Fr 15 Mai 2015 09:58:27 CEST, uli42 wrote:

> Am 15.05.2015 07:09 schrieb "Mike Gabriel" notifications@github.com:
> 
> > > I have managed to fix that now
> > > (
> > > https://github.com/uli42/nx-libs/commit/61018cd39d02fbda1f2f766d8320c53866fa55d3
> > > ).
> > 
> > Cool. Will test that later today when at uni.
> 
> At uni? I had thought you are running a business... :-)

I am doing both (50:50)...

> > > Please also have a look at my most current commit
> > > 
> > > https://github.com/uli42/nx-libs/commit/ae8230ce3add2f62b4d8a294fb9a375a6e530ed4
> > > .
> > 
> > I am not sure that I understand this commit by just looking at the
> > patch. Need to re-read it later.
> 
> No need to reread, this was just tell you there's a newer commit already.

Ok.

> > > > > Regarding the "resize on the left corners" issue: I cannot reproduce
> > > > > it with Ubuntu 14.04 running Unity Desktop (with compiz as window
> > > > > manager). It works absolutely flawless in both single nxagent run
> > > > > and complete x2go session. So this looks like a window manager issue
> > > > > on your side. What window manager are you using?
> > > > 
> > > > The marco window manager shipped with MATE desktop. The marco window
> > > > manager is a metacity fork IIRC.
> > > 
> > > Oh, I have never heard about marco. Can you reproduce the issue with
> > > another WM?
> > 
> > I will check with another WM today, too.
> 
> OK.

I have tested your latest patchset with various desktop shells (and  
thus: various window managers) inside the windowed NX desktop session,  
now:

```
 * KDE4 (KWin):
     * works perfectly
 * XFCE:
     * works perfectly
 * MATE desktop (marco):
     * the previously reported issue (problems when resizing via  
```

the NX desktop sessions via the left-side window border) has now  
vanished
         \* only left issue: when moving the NX session window, the  
MATE panel and maximized windows fully adapt, but the desktop  
background image does not rescale to the newly intersected Xinerama  
coordinates.
         \* -> let's consider that as an issue in the marco window manager
     \* LXDE's window manager (openbox):
         \* background image does some funny rescaling/tiling stuff  
when moving/resizing the session window
         \* lxpanel does not resize immediately (a know issue in X2Go  
desktop sessions)
         \* -> this will require some work on the LXDE side, I presume,  
let's ignore that for now...

I'd say let's got for merging your code...

## 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/freebusy/m.gabriel%40das-netzwerkteam.de.xfb

**Comment by uli42** [comment]
Am Freitag, 15. Mai 2015 schrieb

**Comment by uli42** [comment]
On Fri, May 15, 2015 at 1:22 PM, Mike Gabriel notifications@github.com wrote:

> I have tested your latest patchset with various desktop shells (and
> thus: various window managers) inside the windowed NX desktop session,
> now:
> - KDE4 (KWin):
> - works perfectly

I had some kde4 crashes in Krandr code while testing. I am using
(K)Ubuntu 14.04 so maybe this is fixed already.

> - XFCE:
> - works perfectly

good

> - MATE desktop (marco):
> - the previously reported issue (problems when resizing via
>   the NX desktop sessions via the left-side window border) has now
>   vanished

ok

> - only left issue: when moving the NX session window, the
>   MATE panel and maximized windows fully adapt, but the desktop
>   background image does not rescale to the newly intersected Xinerama
>   coordinates.
> - -> let's consider that as an issue in the marco window manager
> - LXDE's window manager (openbox):
> - background image does some funny rescaling/tiling stuff
>   when moving/resizing the session window

I've seen that,too, but I'd say this is correct. LXDE/Openbox takes
the smallest head and tiles the wallpaper accordingly for that head.

> - lxpanel does not resize immediately (a know issue in X2Go
>   desktop sessions)
> - -> this will require some work on the LXDE side, I presume,
>   let's ignore that for now...

agreed.

> I'd say let's got for merging your code...

No, not so fast. There are a couple of things that have to be
tested/fixed before:
- does not properly work when the real X11 server does not offer the
  XINERAMA extension
- reconnect is completely untested. Needs to be tested with different
  client side xinerama settings.
- xrandr values are correct when the first move or resize is done -
  but not before. I am still investigating why
- disabling xinerama with -xinerama is not working. You can only
  disable RANDR altogether. So you cannot run without xinerama
  currently. -xinerama option is recognized but the flag is reset
  somewhere in nxagent so I cannot check for it . I have not found out
  yet what's going on here.
- I have not yet tested in detail how clients speaking only randr 1.1
  are working with the modified nxagent. As randr 1.1 has limited
  possibilities I am even unsure what they should be getting...
- I have seen some strange behaviour twice so I guess there's some
  kind of race condition in the code.
- I have not tested yet what happens in NX when xinerama changes on
  the real X server. nxagent should get a notification about that and
  update the screen. When that is working caching the xinerama setting
  of the real X server should be implemented.
- nx creates multiple virtual output devices but only the first one
  offers the default resolutions. So you can call xrandr -s <some
  resolution> only for the first output but not for the second, third...
- probably more.

A lot to do...

Uli

**Comment by sunweaver** [comment]
Ah... ok. Thanks for bringing up all those still pending issues.

I actually just stumbled over another one while doing so triaging of old NX bugs on the X2Go bug tracker. Can you take a look at that one, too?
http://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=417

THANKS!
Mike

**Comment by uli42** [comment]
On Fri, May 15, 2015 at 2:47 PM, Ulrich Sibiller uli42@gmx.de wrote:

A small update to let you know about my progress:

> - does not properly work when the real X11 server does not offer the
>   XINERAMA extension

Fixed, I think

> - reconnect is completely untested. Needs to be tested with different
>   client side xinerama settings.

still untested

> - xrandr values are correct when the first move or resize is done -
>   but not before. I am still investigating why

this is still not working

> - disabling xinerama with -xinerama is not working. You can only
>   disable RANDR altogether. So you cannot run without xinerama
>   currently. -xinerama option is recognized but the flag is reset
>   somewhere in nxagent so I cannot check for it . I have not found out
>   yet what's going on here.

Fixed.

> - I have not yet tested in detail how clients speaking only randr 1.1
>   are working with the modified nxagent. As randr 1.1 has limited
>   possibilities I am even unsure what they should be getting...

I have tested that, it reports the state of the first output, even if
that is disconnected (can be tested with the --q1 parameter of
xrandr). This was working with the old LD_LIBRARY_PATH approach, so I
still must find a solution to this.

> - I have seen some strange behaviour twice so I guess there's some
>   kind of race condition in the code.

I think this is fixed. I have not seen it again.

> - I have not tested yet what happens in NX when xinerama changes on
>   the real X server. nxagent should get a notification about that and
>   update the screen. When that is working caching the xinerama setting
>   of the real X server should be implemented.

Fixed. Maybe I'll reimplement this in a better way.

> - nx creates multiple virtual output devices but only the first one
>   offers the default resolutions. So you can call xrandr -s <some
>   resolution> only for the first output but not for the second, third...

still not fixed

Uli

**Comment by sunweaver** [comment]
@uli42: thanks for the update on this. I posted to you privately instructions for continueing this PR on a cleaned-up branch including the libNX_Xrandr removal PR. Hope that provides some help. THANKS for your work on this!!!

**Comment by sunweaver** [comment]
@uli42: I know you have been working on the X.org 7.0 code tree stuff, but... Do you think that the Xinerama/Xrandr patch here is suitable for merging into nx-libs 3.6.x? I'd be happy about a little feedback.

**Comment by uli42** [comment]
On Tue, Sep 22, 2015 at 10:12 AM, Mike Gabriel notifications@github.com wrote:

> @uli42: I know you have been working on the X.org 7.0 code tree stuff, but... Do you think that the Xinerama/Xrandr patch here is suitable for merging into nx-libs 3.6.x? I'd be happy about a little feedback.

Well, randr-wise it is working well as far as I can tell. However, it
still needs testing. Especially the reconnect has never been tested by
me. I'd consider it beta.

Uli

**Comment by sunweaver** [comment]
Hi Uli,

thanks for feedback. The complete 3.6.x is currently in some sort of a beta phase. So it really fits in well. I currently have a customer project about Xinerama and X2Go, so I will do quite a bit of testing. However, I am unsure if I will provide the old approach from X2Go or your new and better approach.

Shall I merge your code or do you have time for a pull request? (I'd prefer the author of the code to file a pull request, for the sake of a good commit history concerning authorship of the code).

**Pull request closed without merging**
