### PR TITLE
libNX_xext: Drop unused extensions.

### PR DESCRIPTION
**Pull request by sunweaver**
Further investigation showed, that actually the only used client side extension code from libNX_Xext is the XShape extension. Thus, all other client side extension got dropped now.

Before reviewing this PR, the following PRs need to be reviewed:
https://github.com/ArcticaProject/nx-libs/pull/93
https://github.com/ArcticaProject/nx-libs/pull/102
https://github.com/ArcticaProject/nx-libs/pull/106
https://github.com/ArcticaProject/nx-libs/pull/109
https://github.com/ArcticaProject/nx-libs/pull/120

### CODE REVIEW

**Comment by uli42** [comment]
So isn't it time to switch to static linking for libNX\* now?

Vom Smartphone gesendet.

----- Ursprüngliche Nachricht -----
Von: "Mike Gabriel" notifications@github.com
Gesendet: ‎05.‎05.‎2016 22:53
An: "ArcticaProject/nx-libs" nx-libs@noreply.github.com
Betreff: [ArcticaProject/nx-libs] libNX_xext drop unused extensions (#121)

Further investigation showed, that actually the only used client side extension code from libNX_Xext is the XShape extension. Thus, all other client side extension got dropped now.

You can view, comment on, or merge this pull request online at:
  https://github.com/ArcticaProject/nx-libs/pull/121
Commit Summary
gcc: Build using -std=c99 instead of -ansi. 
NXwindow.c: Don't set w and h, not used later on. 
fix-patch-whitepspace: Copy script from X.Org's xserver Git repo. 
Rename region macros to eliminate screen argument 
Move mi/miregion.c to dix/region.c 
Change region implementation from macros to inline functions. 
pixman-devel: Build against shared library pkg-config(pixman-1). 
Change region implementation names to eliminate the 'mi' prefix 
Add REGION_ macros for source compatibility with existing drivers. 
hw/nxagent/Drawable.c: RegionNumRects returns int, not long int anymore. 
hw/nxagent/Clipboard.c: The result variable is only needed when combiled with -DDEBUG. 
hw/nxagent/Splash.c: Drop unused variable declaration "XPoint m[12];". 
hw/nxagent/Rootless.c: Type cast type Atom to type long unsigned int before handing it over to %lu in fprintf(). 
hw/nxagent/Extension.c: Don't declare pRandRScrPriv without using it later on. 
hw/nxagent/Pixmap.c: pBool pointer is only required when compiled in -DTEST mode. 
hw/nxagent/Window.c: Don't declare "XWindowChanges changes;" and later not use it. 
hw/nxagent/Screen.c: Correctly use already defined MIN/MAX macros. 
hw/nxagent/Screen.h: Provide prototype for nxagentAdjustRandRXinerama(). Avoid implicit-declaration compiler warning. 
hw/nxagent/Screen.c: Drop various unused variables. 
hw/nxagent/Screen.c: Cast proper types before handing values over to fprintf(). 
hw/nxagent/_.c: Drop various declarations of unused ScreenPtr pScreen. 
hw/nxagent/Keyboard.c: Don't declare and set XkbDescPtr xkb if not used later on. 
hw/nxagent/Handlers.c: Don't declare and assign result variable if not used later on. 
hw/nxagent/Keyboard.c: The ret variable is only used later on when compiled with -DTEST. 
hw/nxagent/NXglyphcurs.c: Don't declare and set gcval, if not being used later on. 
hw/nxagent/NXpicture.c: Don't declare anything in empty function nxagentReconnectPictFormat. 
hw/nxagent/NXdixfonts.c: Don't include <X11/fonts/fontstruct.h>. No symbol needed from that header file. 
Adapt API for MakeAtom() and CopyISOLatin1Lowered to latest changes in X.org. 
hw/nxagent/NXdixfonts.c: Fix implicit declaration for register_fpe_functions(). 
HAVE_STDINT_H: Always include <stdint.h>. 
hw/nxagent/NXrender.c: Don't declare and assign the colors variable, if not used later on. 
hw/nxagent/Display.c: Don't declare and assign packMethod / packQuality if not used later on. 
hw/nxagent/Events.c: Only declare and assign message_data and box variables if compiled with -DTEST / -DDEBUG (plus drop commented out code). 
hw/nxagent/GC.c: Don't declare and assign flexibility variable if not used later on. 
hw/nxagent/GCOps.c: Don't declare and assign oldDstxyValue if not used later on. 
hw/nxagent/Colormap.c: Don't declare and assign flexibility variable if not used later on. 
hw/nxagent/Window.c: Initialize tmp_mask and attributes.event_mask with NoEventMask. 
hw/nxagent/Keystroke.c: Fix warning: pointer type mismatch in conditional expression. 
hw/nxagent/NXmiexpose.c: Initialize all items of the newValues[] array. 
hw/nxagent/Events.c: Avoid '#endif <empty line> #ifdef DEBUG' blocks. 
hw/nxagent/Holder.c: Define Pixmap from XlibPixmap before including hw/nxagent/X11/include/xpm_nxagent.h. 
hw/nxagent/Display.c: Define Pixmap from XlibPixmap before including Icons.h (which includes hw/nxagent/X11/include/xpm_nxagent.h). 
hw/nxagent/Display.c: Avoid incompatible pointer type. 
Drop X11 extensions not shipped with recent X.Org server versions anymore: 
XEVIE: Drop all Xserver code blocks that relate to removed XEVIE extension. 
XAPPGROUP: Drop all Xserver code blocks that relate to removed XAPPGROUP extension. 
TOGCUP: Drop all Xserver code blocks that relate to removed TOGCUP extension. 
XFree86DGA: Drop all Xserver code blocks that relate to removed XFree86DGA extension. 
FONTCACHE: Drop all Xserver code blocks that relate to removed FONTCACHE extension. 
EVI: Drop all Xserver code blocks that relate to removed EVI extension. 
LBX: Drop all Xserver code blocks that relate to removed LBX extension. 
MULTIBUFFER: Drop all Xserver code blocks that relate to removed MULTIBUFFER extension. 
XF86VIDMODE: Drop all Xserver code blocks that relate to removed XF86VIDMODE extension. 
MITMISC: Drop all Xserver code blocks that relate to removed MITMISC extension. 
XF86MISC: Drop all Xserver code blocks that relate to removed XF86MISC extension. 
XFreeXDGA: Drop all Xserver code blocks that relate to removed XFreeXDGA extension. 
XTRAP: Drop all Xserver code blocks that relate to removed XTRAP extension. 
nxcomshad/Makefile.in: Only install Shadow.h as publicly available header file. 
nxcomp/Makefile.in: Only install MD5.h, NX.h, NXalert.h, NXpack.h, NXproto.h and NXvars.h as publicly available header files. 
nx-X11/programs/Xserver: Include nxcomp{,ext,shad} headers like one would do with system-wide shared libraries. 
Xserver/dix/Imakefile: Serialize parameters and make Imakefile changes more trackable. 
hw/nxagent/NXextension.c: Shrink file, drop duplicate code that is indentically found in dix/extension.c. 
Xserver/hw/nxagent: Drop NXcompositeext.h, it is a duplicate of nx-X11/include/extensions/composite.h. 
NXcomposite.h: Move fake header file NXcomposite.h to hw/nxagent/X11/include/ and drop all symbols that are not explicitly used by nxagent. 
hw/nxagent/NXdamage.c: Shrink file, drop duplicate code that can identically be found in miext/damage/damage.c. 
hw/nxagent/NXmiwindow.c: Drop complete file. 
hw/nxagent/NXmitrap.c: Shrink file, drop duplicate code that can identically be found in render/mitrap.c. 
hw/nxagent/NXmiglyph.c: Shrink file, drop code that can be identically found in render/miglyph.c. 
Xserver/mi/Imakefile: Serialize parameters and make Imakefile changes more trackable. 
hw/nxagent/Pixmaps.h: Make RESTYPE well-defined by adding resource.h to includes. 
hw/nxagent/NXmiexpose.c: Shrink file, drop duplicate code that can identically be found in mi/miexpose.c. 
hw/nxagent/NXpicture.c: Shrink file, drop duplicate code that can identically be found in render/picture.c. 
hw/nxagent/NXxvdisp.c: Shrink file, drop duplicate code that can identically be found in Xext/xvdisp.c. 
Xserver/GL/glx/Imakefile: Serialize parameters and make Imakefile changes more trackable. 
hw/nxagent/NXglxext.c: Shrink file, drop duplicate code that can identically be found in GL/glx/glxext.c. 
hw/nxagent/NXwindow.c: Shrink file, drop duplicate code that can identically be found in dix/window.c. 
Xserver/dix/window.c: Don't reintroduce build warnings with previous commit due to now-unnecessary assignements of pScreen pointers. 
hw/nxagent/NXshm.c: Shrink file, drop duplicate code that can identically be found in Xext/shm.c. 
hw/nxagent/NXresource.c: Shrink file, drop duplicate code that can identically be found in dix/resource.c. 
NXrenderint.h: Move into subfolder X11/include/ and rename to Xrender_nxagent.h. (Like we have done with all other non-public Xlib related header files that are required for building nxagent. 
hw/nxagent/NX{glyphstr,picturestr}.h: Don't ship the complete header files in nxagent's code base. Rather replace structures we need modified only. 
hw/nxagent/NXrender.c: Shrink file, drop duplicate code that can identically be found in render/render.c. 
hw/nxagent/NXglyphcurs.c: Shrink file, drop duplicate code that can identically be found in dix/glyphcurs.c. 
hw/nxagent/NXglyph.c: Shrink file, drop duplicate code that can identically be found in render/glyph.c. 
hw/nxagent/NXevents.c: Shrink file, drop duplicate code that can identically be found in dix/events.c. 
hw/nxagent/NXproperty.c: Shrink file, drop duplicate code that can identically be found in dix/property.c. 
hw/nxagent/NXdispatch.c: Shrink file, drop duplicate code that can identically be found in dix/dispatch.c. 
hw/nxagent/NXdixfonts.c: Shrink file, drop duplicate code that can identically be found in dix/dixfonts.c. Also remove NX'ish code from dix/dixfonts.c. 
hw/nxagent/NX_.c: Amend re-introduced nxagent warnings by fixing the corresponding code section in files included from "somewhere" in nx-X11/programs/Xserver/. 
hw/nxagent: Drop code referring to the following removed Xserver extensions: XAPPGROUP, LBX, XEVIE. 
debian/patches: Refresh 102_xserver-xext_set-securitypolicy-path.debian.patch. 
libNX_Xext: Drop more Xext extensions: DPMS, XShm, XTestExt1, XSync, XSecurity. 
packaging: Adapt RPM and Debian packaging to removal of libNX_Xext code. 
File Changes
M debian/control (2) 
M debian/libnx-xext-dev.install.in (30) 
M debian/libnx-xext6.symbols (216) 
M debian/libxcomp-dev.install.in (2) 
M debian/libxcompshad-dev.install.in (10) 
M debian/nx-x11proto-xext-dev.install.in (2) 
M debian/patches/016_nx-X11_install-location.debian.patch (2) 
M debian/patches/102_xserver-xext_set-securitypolicy-path.debian.patch (2) 
M debian/rules (15) 
A fix-patch-whitespace (4) 
M nx-X11/config/cf/README (5) 
M nx-X11/config/cf/X11.tmpl (127) 
M nx-X11/config/cf/linux.cf (4) 
M nx-X11/config/cf/xorg.cf (35) 
M nx-X11/include/extensions/Imakefile (39) 
D nx-X11/include/extensions/MITMisc.h (66) 
D nx-X11/include/extensions/XEVI.h (64) 
D nx-X11/include/extensions/XEVIstr.h (98) 
D nx-X11/include/extensions/XLbx.h (155) 
D nx-X11/include/extensions/Xag.h (114) 
D nx-X11/include/extensions/Xagsrv.h (76) 
D nx-X11/include/extensions/Xagstr.h (182) 
D nx-X11/include/extensions/Xcup.h (69) 
D nx-X11/include/extensions/Xcupstr.h (109) 
D nx-X11/include/extensions/Xdbe.h (136) 
D nx-X11/include/extensions/Xevie.h (78) 
D nx-X11/include/extensions/Xeviestr.h (165) 
D nx-X11/include/extensions/Xinerama.h (76) 
D nx-X11/include/extensions/fontcache.h (106) 
D nx-X11/include/extensions/fontcacheP.h (40) 
D nx-X11/include/extensions/fontcachstr.h (130) 
D nx-X11/include/extensions/lbxbuf.h (51) 
D nx-X11/include/extensions/lbxbufstr.h (45) 
D nx-X11/include/extensions/lbxdeltastr.h (105) 
D nx-X11/include/extensions/lbximage.h (151) 
D nx-X11/include/extensions/lbxopts.h (133) 
D nx-X11/include/extensions/lbxstr.h (931) 
D nx-X11/include/extensions/lbxzlib.h (64) 
D nx-X11/include/extensions/mitmiscstr.h (70) 
D nx-X11/include/extensions/multibuf.h (317) 
D nx-X11/include/extensions/multibufst.h (609) 
D nx-X11/include/extensions/xf86dga.h (264) 
D nx-X11/include/extensions/xf86dga1.h (140) 
D nx-X11/include/extensions/xf86dga1str.h (194) 
D nx-X11/include/extensions/xf86dgastr.h (344) 
D nx-X11/include/extensions/xf86misc.h (172) 
D nx-X11/include/extensions/xf86mscstr.h (238) 
D nx-X11/include/extensions/xf86vmode.h (322) 
D nx-X11/include/extensions/xf86vmstr.h (562) 
D nx-X11/include/extensions/xtrapbits.h (83) 
D nx-X11/include/extensions/xtrapddmi.h (115) 
D nx-X11/include/extensions/xtrapdi.h (507) 
D nx-X11/include/extensions/xtrapemacros.h (387) 
D nx-X11/include/extensions/xtraplib.h (128) 
D nx-X11/include/extensions/xtraplibp.h (142) 
D nx-X11/include/extensions/xtrapproto.h (168) 
M nx-X11/lib/X11/XlibInt.c (6) 
M nx-X11/lib/X11/Xlibint.h (2) 
D nx-X11/lib/Xext/DPMS.c (293) 
M nx-X11/lib/Xext/Imakefile (15) 
D nx-X11/lib/Xext/MITMisc.c (133) 

[Die ursprüngliche Nachricht wird nicht vollständig eingefügt.]

**Comment by sunweaver** [comment]
@uli42: I guess so. It will create a PR for it, once we come to the tidying up phase before the release.

**Comment by sunweaver** [comment]
@vatral: Hi Vadim. Could you (if possible on Monday or earlier) do a code review of PR #121 [1]?

Thanks,
Mike

[1] https://github.com/ArcticaProject/nx-libs/pull/121

**Comment by vatral** [comment]
I will try, though I am not sure I am familiar enough yet with the codebase to do a thorough job. Some things I have noticed:
- nx-X11/lib/Xext/Imakefile: Formatting and indentation has changed. This is a bit annoying for review purposes, though it should make things easier for later ones. I assume there's some sort of new formatting standard here.
- Code related to SHM in the Imakefile has changed, this seems outside the scope of the removal of the listed extensions. XShm is always now built in, and the option to choose it does nothing. This isn't mentioned in the description, and seems like the sort of thing that should go separately.
- What is the $(NULL) thing? I am confused by what it does.

**Comment by Ionic** [comment]
The `$(NULL)` thing is a bit of a hack. We define the variable to an empty string and use it as the very last element in a list afterwards. This has the benefit of making list manipulations more easily viewable in diffs.

Take

``` make
LIST = a \
       b \
       c
```

If this is to be extended by a "d" element as the last list element, the diff would look like this (affecting both c and the new d elements):

``` diff
--- test    2016-06-27 18:04:29.000000000 +0200
+++ test2   2016-06-27 18:04:41.000000000 +0200
@@ -1,3 +1,4 @@
 LIST = a \
        b \
-       c
+       c \
+       d
```

However, by appending `$(NULL)` first:

``` make
LIST = a \
       b \
       c \
       $(NULL)
```

Further diffs can be simplified, as only one line is changing:

``` diff
--- test    2016-06-27 18:09:31.000000000 +0200
+++ test2   2016-06-27 18:09:40.000000000 +0200
@@ -1,4 +1,5 @@
 LIST = a \
        b \
        c \
+       d \
        $(NULL)
```

**Comment by sunweaver** [comment]
@vatral: thanks for feedback. Taking a look again myself and I think we should split this one commit into at least two or three. Will do that now.

**Comment by sunweaver** [comment]
@vatral: please take a second glance, if possible today. Thanks.

Changes:
- split out a packaging fix for dpmsstr.h and securstr.h
- serialize Imakefile before changing it
- bundle removal of code with packaging update (splitting those changes up in two commits does not make much sense)

**Comment by vatral** [comment]
Hello,

I checked it out again and it looks good to me.

**Pull request merged**
