### PR TITLE
Xserver/randr/rrinfo.c: Don't call RRScanOldConfig() from RANDR_10_INTERFACE. CRTC and OUTPUT setup happens in nxagent's Screen.c file.

### PR DESCRIPTION
**Pull request by sunweaver**
Fixes ArcticaProject/nx-libs#293.

### CODE REVIEW

**Comment by sunweaver** [comment]
This PR is still flawed, marking as invalid for now...

**Comment by sunweaver** [comment]
@uli42: @vatral: Please test and review this new approach (omitting RRScanOldConfig() call) to fix #293. Thanks!

**Comment by sunweaver** [comment]
Hi Uli,

Test cases:

  * ./nxagent -xinerama :1
  * ./nxagent -extension XINERAMA :1
  * ./nxagent -disablexineramaextension :1

-> panoramiX functionality exists in the NX session, handled by RandR extension

  * ./nxagent -rrxinerama :1

-> panoramiX functionality exists in the NX session, handled by XINERAMA extension

  * ./nxagent -xinerama -rrxinerama :100: 

-> panoramiX functionality is gone, only NX1 exists in the NX session

So, I'd say: all tests passed. Agree?

Mike

**Comment by sunweaver** [comment]
On one of my machines I observed plenty of crashes at session startup. This machine has been cured with the fix provided by this PR.

**Comment by uli42** [comment]
Can you provide some information about that very system? I am wondering what exactly triggers/triggered these crashes.

**Comment by sunweaver** [comment]
@uli42: that machine was a very plain Debian jessie, with nx-libs from our nightlies + X2Go Server from the nightlies. The system is an amd64 installation.

The system is a newly rented server at Hetzner's, so the installation was really fresh. Also the HOME of the user was created anew. So, the ideal test case.

**Comment by uli42** [comment]
So can you replicate the crashes?

**Comment by sunweaver** [comment]
Hi Ulrich,

On  Mo 06 Feb 2017 13:22:34 CET, Ulrich Sibiller wrote:

> So can you replicate the crashes?

On that machine: yes. No resources to test on multiple machines.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by sunweaver** [comment]
Superseded by PR 323, this marking this one invalid and closing.

**Pull request closed without merging**
