### PR TITLE
Pr/various backports

### PR DESCRIPTION
**Pull request by uli42**
Fixes for #541, #542, #558 and some more fixes without issue

### CODE REVIEW

**Review by sunweaver — CHANGES_REQUESTED** [review]
Thanks for backporting those fixes.

However, I would like to see the following commit msg pattern:

```
<nx-libs first-line msg (equals first line xorg msg)>

 Backported from X.org:

 <X.org commit header>

     <commit msg from X.org, indented by 4 chars>

 Backported-to-NX-by: <you and your mailaddress>

 Fixes this-and-that/project#<nnn>
```

For an example see: 
 https://github.com/ArcticaProject/nx-libs/commit/565421ba18a09d20620e01fc877915a8b09a3735

**Comment by sunweaver** [comment]
@uli42: When porting patches from X.org: most important is having the X.org commit hash in the nx-libs commit msg text for later reference. THANKS!

**Comment by uli42** [comment]
reworked, added some more backports, rebased

**Review by Ionic — APPROVED** [review]

**Comment by Ionic** [comment]
Going to fixup some commit messages before the actual merge.

**Comment by Ionic** [comment]
We need spaces after hashes so that github doesn't automatically link our bug reports to the mentioned numbers.

Also fixed up some commit authors.

**Pull request merged**
