### PR TITLE
nxcompshad: Drop Cygwin/Win32 support. Has been untested and unused f…

### PR DESCRIPTION
**Pull request by sunweaver**
…or a long time.

 This code can be reactivated any time in the future once
 some potential maintainer turns up and makes this work
 on the MS Windows / Cygwin platform.

### CODE REVIEW

**Comment by Ionic** [comment]
Hmm, yeah, okay, but what about the `__CYGWIN32__`/`WIN32` code segments in the other source files? Would also make sense to remove them, right?

**Comment by sunweaver** [comment]
On  Do 24 Aug 2017 03:49:22 CEST, Mihai Moldovan wrote:

> Hmm, yeah, okay, but what about the `__CYGWIN32__`/`WIN32` code  
> segments in the other source files? Would also make sense to remove  
> them, right?

@Ionic: good point. I'll do that (for nxcompshad only, this is) tomorrow.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by sunweaver** [comment]
> Hmm, yeah, okay, but what about the __CYGWIN32__/WIN32 code segments in the other source files? Would also make sense to remove them, right?

The __CYGWIN32__/WIN32 clean-up in nxcompshad is now complete. Please revisit.

**Review by Ionic — APPROVED** [review]

**Comment by sunweaver** [comment]
On  Sa 26 Aug 2017 23:32:22 CEST, Mihai Moldovan wrote:

> Ionic approved this pull request.

Branch has been rebased, ready for merging.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Pull request merged**
