### PR TITLE
Backport X.org memory handling

### PR DESCRIPTION
**Pull request by sunweaver**
This PR backports memory handling changes from X.org. This PR basically backports three major commits from X.org's Xserver:

```
     commit cad9b053d52f62432dfd70e42e0240de77027cae
     Author: Adam Jackson <ajax@redhat.com>
     Date:   Tue Jul 8 13:24:25 2014 -0400

        os: Remove deprecated malloc/free wrappers

        Reviewed-by: Alex Deucher <alexander.deucher@amd.com>
        Signed-off-by: Adam Jackson <ajax@redhat.com>

     commit e983848ab44b0769f97f6207f1aa8b4f127be6a9
     Author: Mikhail Gusarov <dottedmag@dottedmag.net>
     Date:   Thu May 6 00:16:24 2010 +0700

        Clean {X,XNF}{alloc,calloc,realloc,free,strdup} from pre-C89 baggage

        C89 guarantees alignment of pointers returned from malloc/calloc/realloc, so
        stop fiddling with alignment manually and just pass the arguments to library
        functions.

        Also convert silent error when negative size is passed into function into
        warning in log file.

        Signed-off-by: Mikhail Gusarov <dottedmag@dottedmag.net>
        Reviewed-by: Peter Hutterer <peter.hutterer@who-t.net>

commit 3f3ff971ecff9936cebafc813af9193b97bba89c
Author: Mikhail Gusarov <dottedmag@dottedmag.net>
Date:   Thu May 6 01:44:06 2010 +0700

    Replace X-allocation functions with their C89 counterparts

    The only remaining X-functions used in server are XNF*, the rest is converted to
    plain alloc/calloc/realloc/free/strdup.

    X* functions are still exported from server and x* macros are still defined in
    header file, so both ABI and API are not affected by this change.

    Signed-off-by: Mikhail Gusarov <dottedmag@dottedmag.net>
    Reviewed-by: Peter Hutterer <peter.hutterer@who-t.net>
```

### CODE REVIEW

**Comment by uli42** [comment]
Won't this x*alloc stuff complicate upgrading the code? I agree with this cleanup in principle but is this the right time for that?

**Comment by vatral** [comment]
Looks good, though a fair amount of references to Xcalloc, Xrealloc, xfree, and such remain in nx-X11/lib/X11/. I assume this is simply out of the scope of the patch?

**Comment by vatral** [comment]
Everything else looks fine, done with this one.

**Comment by sunweaver** [comment]
> Won't this x*alloc stuff complicate upgrading the code? I agree with this cleanup in principle but is this the 
> right time for that?

@uli42: I think it is the right time. Actually, I would love to have the code tree as similar to X.org as possilble, so that we can pick code parts from X.org directly and that the diff between X.org and nx-X11's Xserver is as minimal as possible.

Also, stuff like ABI changes or coding style should be changed before a major release. So that package maintainers can cherry-pick patches more easily. If we change the coding style (which is on my list, actually) after a release, then backporting patches is a hard endeavour.

**Comment by sunweaver** [comment]
@vtq: libX11 is not in the scope of this PR, indeed. Thus, merging.

**Pull request merged**
