### PR TITLE
Lift Xi to xorg-xserver-7.1/1.1.0 state

### PR DESCRIPTION
**Pull request by uli42**

### CODE REVIEW

**Review by Ionic — CHANGES_REQUESTED** [review]
My only issue with this PR/commit is that it's huge and mostly does non-functional whitespace changes only.

It was really difficult to find spots that may actually change the programs behavior!

Would you mind splitting that up in two commits - one for non-functional changes, the other one for changes that may impact behavior or are in other ways functional?

List of functional changes I detected:
(file) (line old)/(line new)
nx-X11/programs/Xserver/Xi/extinit.c 220/222
nx-X11/programs/Xserver/Xi/extinit.c 775/750
nx-X11/programs/Xserver/Xi/extinit.c 870/840
nx-X11/programs/Xserver/Xi/extinit.c 946/911
nx-X11/programs/Xserver/Xi/stubs.c 202/194
nx-X11/programs/Xserver/Xi/getbmap.c 126/121

**Comment by uli42** [comment]
I can do that. The original idea was to get the code closer to Xorg
upstream by also adding the whitespace changes.

Am 08.02.2018 15:57 schrieb "Mihai Moldovan" <notifications@github.com>:

**Comment by sunweaver** [comment]
On  Do 08 Feb 2018 19:57:26 CET, Ulrich Sibiller wrote:

> I can do that. The original idea was to get the code closer to Xorg
> upstream by also adding the whitespace changes.
>

Which is good. But I agree with Ionic to separate white-space commits  
from functional commits.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
I have split up the commit now. Apart from the functions prototypes without/with void there are no differences to the existing pre-7.1 code.

**Review by sunweaver — APPROVED** [review]
Thanks for splitting up commits. Looks good to me now.

@Ionic: agree?

**Comment by Ionic** [comment]
Haven't looked into this yet, will do so this weekend or next week, including working on the other PRs of this chain.

**Review by Ionic — APPROVED** [review]

**Comment by Ionic** [comment]
Okay. I really meant splitting it up into two unique commits (for non-functional and functional changes), but we'll have to make do with this now.

**Pull request merged**
