### PR TITLE
Include system wide headers for nxcomp, nxcompext, nxcompshad

### PR DESCRIPTION
**Pull request by sunweaver**
Let's prepare for including nxcomp{,ext,shad} headers from a system-wide location.

Before reviewing this PR, the following PRs need to be reviewed:
https://github.com/ArcticaProject/nx-libs/pull/93
https://github.com/ArcticaProject/nx-libs/pull/102
https://github.com/ArcticaProject/nx-libs/pull/106

### CODE REVIEW

**Comment by uli42** [comment]
I'd find it cleaner to include `<nx/NX.h>` instead of `<NX.h>` + extending the include search path elsewhere. Extension includes are included similarly: `<X11/extensions/...>`

**Comment by sunweaver** [comment]
HI Ulrich

On  Do 07 Apr 2016 00:41:34 CEST, Ulrich Sibiller wrote:

> I'd find it cleaner to include <nx/NX.h> instead of <NX.h> +  
> extending the include search path elsewhere. Extension includes are  
> inlcuded similarly: <X11/extensions/...>

Hehehe... I used this way of handling that after looking at the .pc  
files you provided for nxcomp*.

Maybe we should change those first?

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/mailxchange/kronolith/fb.php?u=m.gabriel%40das-netzwerkteam.de

**Comment by uli42** [comment]
On Thu, Apr 7, 2016 at 12:47 AM, Mike Gabriel notifications@github.com wrote:

> HI Ulrich
> 
> On Do 07 Apr 2016 00:41:34 CEST, Ulrich Sibiller wrote:
> 
> > I'd find it cleaner to include <nx/NX.h> instead of <NX.h> +
> > extending the include search path elsewhere. Extension includes are
> > inlcuded similarly: <X11/extensions/...>
> 
> Hehehe... I used this way of handling that after looking at the .pc
> files you provided for nxcomp*.
> 
> Maybe we should change those first?

D'oh.. Seems like I am getting confused by so many changes on
different branches. I am using the nx/.. stuff at the rebase project,
IIRC. So you are right, nxcomp\* should be fixed here.

Uli

**Comment by fcarvajaldev** [comment]
Hi,

After reading your previous comments I would like to confirm that I understood this issue correctly, just to prevent future collisions with our changes in nxcomp. So when you are talking about fixing nxcomp\* I understand that you mean just to fix the inclusion paths in the nxcomp\* pkg-config files in order to be coherent with the option that you finally use in your includes of the headers from nxcomp, nxcompshad and nxcompext.

Am I right or may be other changes related to this in nxcomp*?

Thanks in advance,
Fernando

**Comment by uli42** [comment]
You are right, I am only talking about the include paths. Specifically
this line in nxcomp.pc.in should be changed:

Cflags: -I${includedir} -I${includedir}/nx

to

Cflags: -I${includedir}

All sources need to include <nx/whatever.h> instead of <whatever.h> then.

Uli

**Comment by sunweaver** [comment]
Before reviewing this PR, the following PRs need to be reviewed:
https://github.com/ArcticaProject/nx-libs/pull/102
https://github.com/ArcticaProject/nx-libs/pull/106

**Comment by sunweaver** [comment]
@uli42, @fcarvajaldev: I will soon amend this with a force-push on the PR branch of this pull request. No further action needs to be taken from your side.

**Comment by sunweaver** [comment]
@uli42, @fcarvajaldev: reworked commit pushed.

**Comment by uli42** [comment]
Much better, thanks.

I am wondering a bit about that change:

https://github.com/sunweaver/nx-libs/commit/3fad1db73b2c1314e0b1d69dd550200a4fe849c2#diff-d40dd39f54f717a71c10ee7d1ede8866

Isn't that the opposite of what this patch should do?

**Comment by sunweaver** [comment]
HI Uli,

On  Do 07 Apr 2016 23:36:01 CEST, Ulrich Sibiller wrote:

> Much better, thanks.
> 
> I am wondering a bit about that change:
> 
> https://github.com/sunweaver/nx-libs/commit/3fad1db73b2c1314e0b1d69dd550200a4fe849c2#diff-d40dd39f54f717a71c10ee7d1ede8866
> 
> Isn't that the opposite of what this patch should do?

Why? What do you mean exactly? Not getting your point.

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/mailxchange/kronolith/fb.php?u=m.gabriel%40das-netzwerkteam.de

**Comment by uli42** [comment]
In the Imakefile the nxcomp includes are referred by relative links. Shouldn't the system includes be used here? Or is this a hen/egg  problem?

**Comment by sunweaver** [comment]
Hi Uli,

On  Do 07 Apr 2016 23:58:06 CEST, Ulrich Sibiller wrote:

> In the Imakefile the nxcomp includes are referred by relative links.  
> Shouldn't the system includes be used here? Or is this a hen/egg  
> problem?

Ah, ok. I see what you mean. The Imakefile additions handles creation  
of symlinks in

   nx-X11/exports/include/nx/

That is wanted that way.

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/mailxchange/kronolith/fb.php?u=m.gabriel%40das-netzwerkteam.de

**Comment by sunweaver** [comment]
@uli42: You have already looked at this PR. Can I presume from your earlier comment that you approve this change?

**Comment by uli42** [comment]
Yes, I approve it.

**Pull request merged**
