### PR TITLE
Pr/fix font defines once more2

### PR DESCRIPTION
**Pull request by uli42**

### CODE REVIEW

**Comment by uli42** [comment]
updated by silencing rules

**Comment by sunweaver** [comment]
Hi,

On Sunday, 11 November 2018, Ulrich Sibiller wrote:
> updated by silencing rules
> 

Is this PR ready for review now?

Mike
-- 
Sent from my Jolla

**Comment by uli42** [comment]
yes

**Review by sunweaver — APPROVED** [review]
Merged.

**Comment by sunweaver** [comment]
I added another commit and removed some "; fi" in Makefile's distclean target (and rebased that change with your commit).

Closing this PR manually. The merge is https://github.com/ArcticaProject/nx-libs/commit/1a429016cfea09abe0255dd85a3cff4c7811c287

**Comment by uli42** [comment]
thx!

**Pull request closed without merging**
