### PR TITLE
Pr/code cleanup

### PR DESCRIPTION
**Pull request by uli42**
scope, comment reformatting, condense code

saves ~400 lines

### CODE REVIEW

**Comment by sunweaver** [comment]
I did a nearly-trivial rebase of this PR branch and force-pushed it.

Changes:

  * drop commits to meanwhile dropped Holder.c
  * fix conflicts in Keyboard.c

**Comment by uli42** [comment]
I have squashed a dangling fixup commit after rebasing.

**Review by sunweaver — APPROVED** [review]
Wow. Thanks for this cleanup! LGTM!

**Comment by sunweaver** [comment]
> I have squashed a dangling fixup commit after rebasing.

Ah, ok. Thanks. I think I still got that in my review (I noticed the list of commits being out-of-date while reviewing).

**Pull request merged**
