### PR TITLE
Pr/various2

### PR DESCRIPTION
**Pull request by uli42**

### CODE REVIEW

**Comment by sunweaver** [comment]
@uli42: please rebase this PR branch and let me know when it is ready to be reviewed.

**Comment by uli42** [comment]
Will do next week when returning from vacation

Mike Gabriel <notifications@github.com> schrieb am Di., 27. Aug. 2019,
09:50:

**Comment by sunweaver** [comment]
Ok.

Am Dienstag, 27. August 2019 schrieb Ulrich Sibiller:
> Will do next week when returning from vacation
> 
> Mike Gabriel <notifications@github.com> schrieb am Di., 27. Aug. 2019,
> 09:50:
> 
> > @uli42 <https://github.com/uli42>: please rebase this PR branch and let
> > me know when it is ready to be reviewed.
> >


-- 
Gesendet von meinem Fairphone2 (powered by Sailfish OS).

**Comment by uli42** [comment]
rebased

**Review by sunweaver — APPROVED** [review]
Nice work!!! About to merge this.

**Pull request merged**
