### PR TITLE
Pr/libX11 HEAD

### LINKED ISSUE #400: Upgrade libX11 1.6.5
https://abi-laboratory.pro/tracker/timeline/libx11/

### PR DESCRIPTION
**Pull request by uli42**
update to libX11 1.6.5 (+ plus one patch that came in after 1.6.5)

Fixes #400

### CODE REVIEW

**Review by sunweaver — APPROVED** [review]
@uli42: PR #414 is approved. Please rebase against latest 3.6.x branch. Ionic merged one of my PRs today.

Thanks,
Mike

**Comment by uli42** [comment]
done

**Comment by sunweaver** [comment]
@uli42: nope... You still lack these commits on your branch: 

```
commit 286b4d063ed0ed8fdd764c05f60f5ef584be83c6
Author: Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
Date:   Sat Mar 11 00:48:03 2017 +0100

    dix: Remove insane BC hacks
    
     commit 6b5206e7cb8e5279816b48f014d47d3f03f16972
     Author: Daniel Stone <daniel@fooishbar.org>
     Date:   Fri Jul 18 15:38:10 2008 +0300
    
        dix: Remove insane BC hacks
    
        If your DDX needs a 1bpp mode and doesn't set it up, your DDX is
        incompetent.
    
     Backported-to-NX-by: Mike Gabriel <mike.gabriel@das-netzwerkteam.de>

commit 847794f38eff3c2d639fcc1c5543caa2d0052af2
Author: Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
Date:   Fri Mar 10 16:48:54 2017 +0100

    Move AddScreen() comment where it actually belongs. Should be done in X.org, too.

commit 0b9b212b3eba91a239fb90f19b15793ec6ec81ea
Author: Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
Date:   Fri Mar 10 16:29:24 2017 +0100

    dix: Move AddScreen() over into dispatch.c and introduce init_screen()
    
     Partially pruned out of X.org commits:
    
     commit 987579c930bda803427a28cb82773c389f5110d6
     Author: Peter Hutterer <peter.hutterer@who-t.net>
     Date:   Wed Apr 22 13:26:40 2009 +1000
    
        dix: remove all but main() from main.c
    
        All other functions are pushed into where they seemed to fit.
        main.c is now linked separately into libmain.a and linked in by the various
        DDXs.
    
        Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>
    
     commit 3478af3374abffa0c226ee077fda1fcfc0751e74
     Author: Dave Airlie <airlied@redhat.com>
     Date:   Tue Jun 5 17:01:21 2012 +0100
    
        screen: split out screen init code. (v2)
    
        This is a precursor for reusing this code to init gpu screens.
    
        v2: fixup int check as per Keith's review.
    
        Reviewed-by: Keith Packard <keithp@keithp.com>
        Signed-off-by: Dave Airlie <airlied@redhat.com>
    
     Backported-to-NX-by: Mike Gabriel <mike.gabriel@das-netzwerkteam.de>

```

**Comment by uli42** [comment]
hmm, stange, I have pushed once again...

**Pull request merged**
