### PR TITLE
nx-X11/lib/configure.ac: Assure that the USE_DYNAMIC_XCURSOR macro is defines at build-time.

### PR DESCRIPTION
**Pull request by sunweaver**
…MIC_LC macros are defined at build-time.

 Fixes ArcticaProject/nx-libs#768.

### CODE REVIEW

**Comment by sunweaver** [comment]
@uli42: here is the PR required to fix #768. However, it does not bring us a software cursor in shadow sessions. This has never been that way, anyway, so I presume that a software cursor in shadow sessions needs to be coded as a new feature.

**Comment by uli42** [comment]
Haven't we dropped loadable i18n?

**Comment by sunweaver** [comment]
On  Mi 20 Feb 2019 13:26:15 CET, Ulrich Sibiller wrote:

> Haven't we dropped loadable i18n?

we may have, indeed... let me adapt the PR...

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by sunweaver** [comment]
i18n loadable module part now dropped from the commit

**Comment by uli42** [comment]
`grep -r LOADABLE` over the repo does not find any match for HAVE_LOADABLE_MODULES, so this can be dropped, too.

**Comment by uli42** [comment]
`DLOPEN` and `HAVE_SHL_LOAD` are also found nowhere in the source

**Comment by sunweaver** [comment]
hmmm... I would love to keep it as libX11'ish as possible... The block is a copy+paste from configure.ac in libX11.

**Comment by uli42** [comment]
alright, it won't do any harm, so we can leave it in

**Comment by sunweaver** [comment]
On  Mi 20 Feb 2019 14:08:31 CET, Ulrich Sibiller wrote:

> alright, it won't do any harm, so we can leave it in

Please approve and merge then. Thanks!
Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
will check that tonight (if not sick again...)

**Review by uli42 — APPROVED** [review]
have tested compilation, works as intended

**Pull request merged**
