### PR TITLE
Enable slave socket in server mode

### PR DESCRIPTION
**Pull request by vatral**
Greetings!

This fixes the slave socket not getting enabled on the server side.

### CODE REVIEW

**Comment by uli42** [comment]
Does this refer to any existing issue?

**Comment by vatral** [comment]
Issue created. This fixes #913 

Example with the change:

```
Info: Connection with remote proxy completed.
Info: No proxy cookie was provided for authentication.
Info: Forwarding the real X authorization cookie.
Info: Using LAN link parameters 1536/24/1/0.
Info: Using pack method 'adaptive-9' with session ''.
Info: Not using NX delta compression.
Info: Not using ZLIB data compression.
Info: Not using ZLIB stream compression.
Info: Not using a persistent cache.
Info: Forwarding X11 connections to display ':1'.
Info: Forwarding CUPS connections to port 'tcp:localhost:40002'.
Info: Forwarding auxiliary X11 connections to display ':1'.
Info: Forwarding multimedia connections to port 'tcp:localhost:40001'.
Info: Listening to slave connections on port 'tcp:localhost:63330'.
Session: Session started at 'Fri Feb 14 12:23:04 2020'.
Info: Established X server connection.
Info: Using shared memory parameters 0/0K.

$ netstat -apnt | grep proxy
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:63330         0.0.0.0:*               LISTEN      717620/lt-nxproxy   
tcp        0      0 127.0.0.1:41014         127.0.0.1:4100          ESTABLISHED 717620/lt-nxproxy   
$
```

**Review by uli42 — APPROVED** [review]
LGTM

**Comment by vatral** [comment]
Is there anything left to do to get this merged?

**Comment by uli42** [comment]
On Mon, Mar 2, 2020 at 2:53 PM Vadim Troshchinskiy
<notifications@github.com> wrote:
>
> Is there anything left to do to get this merged?

Not really. The only showstopper is a lack of time at Mike#1's side...

Uli

**Review by sunweaver — APPROVED** [review]
Thanks @vatral for sending the patch.

**Comment by sunweaver** [comment]
> Thanks @vatral for sending the patch.

@vatral: please rebase the PR branch or even better, allow nx-libs maintainers to push to PR branches (there is a switch for that in the Github webUI).

If you will do the rebasing yourself, please wait until tonight (Thu, 7th May), as I will merge more pending PRs within the next hours...

**Comment by sunweaver** [comment]
@vatral: ping?

**Comment by sunweaver** [comment]
Resolved by bdc698b7a6b7a0f46019785c288d1baf5fdc9e2e (cherry-picked from this branch).

**Pull request closed without merging**
