### PR TITLE
Build against X.Org's libXfont (drop nx-X11/lib/font/**).

### PR DESCRIPTION
**Pull request by sunweaver**
This PR drops the shipped-with Xfont library (nx-X11/lib/font/**) and adapts the rest of the nx-X11 code, so it can use the system-wide installed libXfont.

### CODE REVIEW

**Comment by sunweaver** [comment]
Please ignore commit a20e77b, I have already pushed that to the 3.6.x branch.

**Comment by Ionic** [comment]
`nx-X11/config/cf/X11.tmpl`:
- Move programs like `BDFTRUNCATE` and `UCSMAPPREFIX` from the `UseInstalledX11` section into the general non-conditioned scope above. We do want them to be always available (if that makes sense?)
- Delete them also from the else branch and:
  - `FONTC`
  - `MKFONTDIR`
  - `MKFONTSCALE`
  - `UCS2ANY`
  - `BDFTRUNCATE`
    could potentially also be moved up into the non-conditional scope. If they are actually used, also add `xfonts-utils`/`pkgconfig(fontutil)` as a build dep to debs and rpms.

**Comment by Ionic** [comment]
`nx-X11/config/cf/X11.tmpl`:

Is FreeType2 really unneeded now? If yes, everything's fine, otherwise we need to keep the `else` branch of `BuildFreetype2Library` and everything past that until `endif /* UseFreetype2 */`.

**Comment by Ionic** [comment]
The same goes for FontConfig.

**Comment by Ionic** [comment]
`nx-X11/config/cf/host.def`:
- Maybe don't just blindly delete `#define HasFreetyp2` and `HasFontconfig`, if they are still used.

`nx-X11/config/cf/xorgsite.def`:
Dito.

`nx-X11/config/cf/linux.cf`:
- `Freetyp2` bits.

**Comment by sunweaver** [comment]
@Ionic: libfreetype and libfontconfig are used as installed on the build system.

They were only used for building libNX_Xfont.a. This part of the build process has now been removed. libXfont pulls in the required libs (freetype and fontconfig) and is dynamically linked against those.

So, I basically removed everything referring to freetype and fontconfig libraries.

If the build engine were autoconf/autotools, one would have to add pkg-config checks for both libraries, but I don't want to weave that into the imake configuration. For now, I make sure that dependencies get added to the build description files (nx-libs.spec, debian/control).

**Comment by sunweaver** [comment]
> `nx-X11/config/cf/X11.tmpl`:
> - Move programs like `BDFTRUNCATE` and `UCSMAPPREFIX` from the `UseInstalledX11` section 
>   into the general non-conditioned scope above. We do want them to be always available (if that
>   makes sense?)
> - Delete them also from the else branch and:
>   - `FONTC`
>   - `MKFONTDIR`
>   - `MKFONTSCALE`
>   - `UCS2ANY`
>   - `BDFTRUNCATE`
>     could potentially also be moved up into the non-conditional scope. If they are actually used, also 
>     add `xfonts-utils`/`pkgconfig(fontutil)` as a build dep to debs and rpms.

Good point. I'll take a look at that later.

**Comment by Ionic** [comment]
The rules that got removed I was talking about are located in `nx-X11/config/cf/X11.tmpl`:
- `MakeFontScale`
- `MakeFontsDir`
- `MakeFonts`
- `InstallFontsDir`
- `InstallFontObjs`
- `InstallFontAliases`
- etc.

While they can probably be removed, we need to make sure that system fonts are getting used instead.

**Comment by Ionic** [comment]
Okay, I dug deeper and can't find any reference of this stuff being used anywhere else, so your patch is probably fine as-is.

But we can really get rid of at least:
- `FONTC`
- `MKFONTDIR`
- `MKFONTSCALE`
- `UCS2ANY`
- `BDFTRUNCATE`
- `UCSMAPPREFIX`

For some reason, I cannot find any reference to `XCURSORGEN` either, so this can likely also be removed...

**Comment by sunweaver** [comment]
On  Di 21 Apr 2015 23:55:54 CEST, Mihai Moldovan wrote:

> Okay, I dug deeper and can't find any reference of this stuff being  
> used anywhere else, so your patch is probably fine as-is.
> 
> But we can really get rid of at least:
> - `FONTC`
> - `MKFONTDIR`
> - `MKFONTSCALE`
> - `UCS2ANY`
> - `BDFTRUNCATE`
> - `UCSMAPPREFIX`
> 
> For some reason, I cannot find any reference to `XCURSORGEN` either,  
> so this can likely also be removed...

Ok. I just forced-pushed the removal of those vars.

## 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/freebusy/m.gabriel%40das-netzwerkteam.de.xfb

**Comment by sunweaver** [comment]
On  Di 21 Apr 2015 18:27:33 CEST, Mihai Moldovan wrote:

> The rules that got removed I was talking about are located in  
> `nx-X11/config/cf/X11.tmpl`:
> - `MakeFontScale`
> - `MakeFontsDir`
> - `MakeFonts`
> - `InstallFontsDir`
> - `InstallFontObjs`
> - `InstallFontAliases`
> - etc.
> 
> While they can probably be removed, we need to make sure that system  
> fonts are getting used instead.

I checked all of those defines under X11.tmpl and none of the removed  
gets referenced in the remaining nx-X11 code tree.

## 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/freebusy/m.gabriel%40das-netzwerkteam.de.xfb

**Comment by sunweaver** [comment]
On  Di 21 Apr 2015 23:55:54 CEST, Mihai Moldovan wrote:

> For some reason, I cannot find any reference to `XCURSORGEN` either,  
> so this can likely also be removed...

I have another imake cleanup branch here locally already, that will  
get rid of XCURSORGEN references.

## 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/freebusy/m.gabriel%40das-netzwerkteam.de.xfb

**Comment by Ionic** [comment]
`nx-libs.spec`:

In the Fedora/RHEL section: removing `fontconfig-devel` etc. is fine, but we'll need a new
`BuildRequires: libXfont-devel`

I can merge it otherwise, haven't found other problems.

**Comment by sunweaver** [comment]
On  Mi 22 Apr 2015 01:45:52 CEST, Mihai Moldovan wrote:

> `nx-libs.spec`:
> 
> Removing `fontconfig-devel` etc. is fine, but we'll need a new
> `BuildRequires: libXfont-devel`

Good catch! For SUSE RPMs this was already in place, but not for  
fe/epel builds.

> I can merge it otherwise, haven't found other problems.

Thanks! Please go ahead, I just did another force-push.

Mike

## 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/freebusy/m.gabriel%40das-netzwerkteam.de.xfb

**Comment by Ionic** [comment]
Hm, github didn't understand this was a merge. Oh well. Closing manually.

**Pull request merged**
