### PR TITLE
TravisCI: Update from Ubuntu Trusty to Xenial

### PR DESCRIPTION
**Pull request by mjtrangoni**
Hi @sunweaver,

I upgraded the TravisCI's configuration from **Ubuntu Trusty (14.04 LTS)** to **Xenial (16.04)**, and also updated the **Clang** latest version from 6.0 to 7.

@uli42 PTAL, there is some new warnings with Clang-7.

### CODE REVIEW

**Comment by uli42** [comment]
Am Fr., 18. Jan. 2019, 21:18 hat Mario Trangoni <notifications@github.com>
geschrieben:

> Hi @sunweaver <https://github.com/sunweaver>,
>
> I upgraded the TravisCI's configuration from *Ubuntu Trusty (14.04 LTS)*
> to *Xenial (16.04)*, and also updated the *Clang* latest version from 6.0
> to 7.
>
> @uli42 <https://github.com/uli42> PTAL, there is some new warnings with
> Clang-7.
>

Thx, will look into that.

Uli

**Comment by uli42** [comment]
On Fri, Jan 18, 2019 at 9:22 PM Ulrich Sibiller <uli42@gmx.de> wrote:
>
>
>
> Am Fr., 18. Jan. 2019, 21:18 hat Mario Trangoni <notifications@github.com> geschrieben:
>>
>> Hi @sunweaver,
>>
>> I upgraded the TravisCI's configuration from Ubuntu Trusty (14.04 LTS) to Xenial (16.04), and also updated the Clang latest version from 6.0 to 7.
>>
>> @uli42 PTAL, there is some new warnings with Clang-7.

The build environment should be extended by the packages xkbcomp-devel
and quilt, maybe more.

Uli

**Comment by mjtrangoni** [comment]
@uli42 you should open a separated issue on those requirements, so that I can understand the need. IMHO, if this is required, this should be complained by  **autotools**.

**Comment by uli42** [comment]
These are soft requirements, no reason for auto tools to complain...

Am Sa., 19. Jan. 2019, 09:50 hat Mario Trangoni <notifications@github.com>
geschrieben:

**Comment by mjtrangoni** [comment]
@uli42 done. PTAL.

About the Xenial **cppcheck** version, it is now 1.72, so if you want, you could also TAL there.

**Comment by uli42** [comment]
LGTM, please merge

**Comment by uli42** [comment]
please merge

**Review by sunweaver — APPROVED** [review]
LGTM, thus merging.

**Pull request merged**
