### PR TITLE
nxcomp/src/Loop.cpp: Reduce control->TokenSize slightly again in orde…

### PR DESCRIPTION
**Pull request by sunweaver**
…r to fix fragmentation of packages when on VPN (or otherwise encapsulated) connections.

### CODE REVIEW

**Comment by sunweaver** [comment]
@Ionic: please take notice of this PR. It fixes slloooowwwness of nx sessions, when connecting through VPN tunnels. The will slightly reduce SKIA or Cairo based rendering performance again slightly, but the benefit when connecting via VPN is worth the shot.

**Comment by uli42** [comment]
Looks to me that we need a dynamic mode here that determines the
optimal value somehow.

**Comment by sunweaver** [comment]
Hi Uli,

On  Mo 09 Okt 2017 11:56:22 CEST, Ulrich Sibiller wrote:

> Looks to me that we need a dynamic mode here that determines the
> optimal value somehow.

We need the possibility to tweak those values at runtime and  
externally. The nxcomp code should not be overloaded with connection  
checks. This should be done via an external tool that then modifies  
the nxcomp settings on-the-fly.

So for now, this fix should go in IMHO (I am also suffering from this  
flaw when using nested VPN tunnels over ADSL).

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Review by Ionic — APPROVED** [review]

**Comment by realsimix** [comment]
Thanks for the commit!

**Pull request merged**
