### PR TITLE
Use Mesa from Mesa-Upstream Git via git-subtree 

### PR DESCRIPTION
**Pull request by sunweaver**
This PR pulls in a massive commit history from Mesa upstream. The mechanism used is "git-subtree". It may be discussed if Git submodule is more appropriate, but I sense that git-subtree is the more state-of-the-art approach for pulling in Vcs-based 3rd-party projects.

@Ionic: @vatral: @salva: @uli42: @mikedep333: Request for comments!!!

### CODE REVIEW

**Comment by salva** [comment]
@sunweaver: I have been not putting too much attention into NX development lately, so, that may have been already discussed somewhere else, but I am missing the high level plan for getting OpenGL to work over NX.

**Comment by sunweaver** [comment]
Hi Salva,

On Mon Feb 20 15:55:05 2017 GMT+0100, Salvador Fandiño wrote:
> @sunweaver: I have been not putting too much attention into NX development lately, so, that may have been already discussed somewhere else, but I am missing the high level plan for getting OpenGL to work over NX. 

I see a good chance of getting glx 1.4 to work base on this PR. My question is about the best approach for pulling in a Git repo into another's subfolder.

Mike

-- 
Sent from my Fairphone (running Sailfish OS)...

**Comment by uli42** [comment]
I think Salva means a plan for accellerated OpenGL...

Vom Smartphone gesendet.

----- Ursprüngliche Nachricht -----
Von: "Mike Gabriel" <notifications@github.com>
Gesendet: ‎20.‎02.‎2017 19:20
An: "ArcticaProject/nx-libs" <nx-libs@noreply.github.com>
Cc: "Ulrich Sibiller" <uli42@gmx.de>; "Review requested" <review_requested@noreply.github.com>
Betreff: Re: [ArcticaProject/nx-libs] Use Mesa from Mesa-Upstream Git viagit-subtree (#340)

Hi Salva, 

On Mon Feb 20 15:55:05 2017 GMT+0100, Salvador Fandiño wrote: 
> @sunweaver: I have been not putting too much attention into NX development lately, so, that may have been already discussed somewhere else, but I am missing the high level plan for getting OpenGL to work over NX. 

I see a good chance of getting glx 1.4 to work base on this PR. My question is about the best approach for pulling in a Git repo into another's subfolder. 

Mike 

-- 
Sent from my Fairphone (running Sailfish OS)...

**Comment by sunweaver** [comment]
@uli42: @salva: with @narenas: and @vatral we are currently discussing to look at supporting VirtualGL in nx-libs. Everything still not yet even cooking, though.

**Comment by salva** [comment]
> Everything still not yet even cooking

Ah, ok, I though this PR was already part of that plan!

**Comment by uli42** [comment]
No time for a review now, but: why does this pr remove 27000 lines but add 824000 lines? Shouldn't this be more or less the same amount?

**Comment by sunweaver** [comment]
On  Do 02 Mär 2017 15:09:36 CET, Ulrich Sibiller wrote:

> No time for a review now, but: why does this pr remove 27000 lines  
> but add 824000 lines? Shouldn't this be more or less the same amount?

The nx-libs bundle folder nx-X11/extras/Mesa contained only a subset  
of the Mesa library, whereas the Git subtree contains all Mesa files  
of the 6.4.1 release.

I am still unsure about the subtree approach here, but I heard many  
people whine about the git submodule feature and sigh with relief when  
git subtree arrived. So...
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by sunweaver** [comment]
Superseded by just merged PR #467. Thus, closing...

**Pull request closed without merging**
